# deploy.ps1 — Build and upload an Azure Machine Configuration package, then create the policy definition
# Generated by Azure Machine Configuration Builder
#
# Usage:
#   .\deploy.ps1 -ConfigPath .\WindowsServiceMonitoring\
#   .\deploy.ps1 -PackagePath .\output\MyConfig.zip
#
# -ConfigPath  → points to the extracted config folder (contains .mof + policy.json)
#                Builds the ZIP automatically (installs modules, packages, fixes structure)
# -PackagePath → points to a pre-built .zip file (skips the build step)
#
# After the script completes, assign the policy from the Azure Portal or with:
#   $def = Get-AzPolicyDefinition -Name 'MC-<ConfigName>'
#   New-AzPolicyAssignment -Name 'MyAssignment' -PolicyDefinition $def -Scope '/subscriptions/<sub-id>'

#Requires -Version 7.0
#Requires -Modules Az.Accounts, Az.Storage, Az.Resources

[CmdletBinding()]
param(
    [Parameter(ParameterSetName='Official')]
    [string]$OfficialProjectPath,

    [string]$TenantId,

    [switch]$RestoreTools,

    [switch]$AllowReleaseUpgrade,

    [Parameter(ParameterSetName='FromConfig')]
    [string]$ConfigPath,

    [Parameter(ParameterSetName='FromZip')]
    [string]$PackagePath,

    [string]$SubscriptionId,

    [string]$ResourceGroupName,

    [string]$StorageAccountName,

    [string]$StorageResourceGroup,

    [string]$ContainerName = 'guestconfiguration',

    [string]$Location = 'uksouth',

    [ValidateSet('Audit', 'AuditAndSet')]
    [string]$Mode = 'Audit',

    [ValidateSet('UserDelegation', 'SharedKey')]
    [string]$StorageAuthMode = 'UserDelegation',

    [ValidateRange(1, 1095)]
    [int]$SasExpiryDays = 6,

    [switch]$SkipLogin
)

$ErrorActionPreference = 'Stop'

if ($OfficialProjectPath) {
    if (-not $TenantId -or -not $SubscriptionId -or -not $StorageAccountName) {
        throw 'Official authoring requires explicit TenantId, SubscriptionId and StorageAccountName.'
    }
    if ($StorageAuthMode -ne 'UserDelegation') { throw 'Official authoring uses Microsoft Entra ID, without Shared Key fallback.' }
    & (Join-Path $PSScriptRoot 'scripts/deploy.ps1') -ProjectPath $OfficialProjectPath -TenantId $TenantId `
        -SubscriptionId $SubscriptionId -StorageAccountName $StorageAccountName -ContainerName $ContainerName `
        -SasExpiryDays $SasExpiryDays -SkipLogin:$SkipLogin -RestoreTools:$RestoreTools -AllowReleaseUpgrade:$AllowReleaseUpgrade
    return
}

if ($StorageAuthMode -eq 'UserDelegation' -and $SasExpiryDays -gt 6) {
    throw 'User delegation SAS lifetime must be 1-6 days (the delegation key limit is 7 days). Use explicit SharedKey mode only if your storage policy permits it.'
}

# ─── Ensure $env:TEMP is set (Linux doesn't set it by default) ───────────────
if (-not $env:TEMP) { $env:TEMP = [System.IO.Path]::GetTempPath() }

# ─── Validate inputs ─────────────────────────────────────────────────────────

if (-not $ConfigPath -and -not $PackagePath) {
    Write-Error "Specify either -ConfigPath (folder with .mof) or -PackagePath (pre-built .zip)"
    exit 1
}

if ($ConfigPath -and $PackagePath) {
    Write-Error "Specify only one of -ConfigPath or -PackagePath, not both"
    exit 1
}

# ─── Build Package (if -ConfigPath) ──────────────────────────────────────────

if ($ConfigPath) {
    if (-not (Test-Path $ConfigPath -PathType Container)) {
        Write-Error "Config folder not found: $ConfigPath"
        exit 1
    }

    $configDir = Resolve-Path $ConfigPath
    $mofFile = Get-ChildItem -Path $configDir -Filter '*.mof' | Select-Object -First 1
    if (-not $mofFile) {
        Write-Error "No .mof file found in $configDir"
        exit 1
    }

    $configName = $mofFile.BaseName
    $packageVersion = '1.0.0'
    $metadataPath = Join-Path $configDir "$configName.metaconfig.json"
    if (Test-Path -LiteralPath $metadataPath) {
        $metadata = Get-Content -LiteralPath $metadataPath -Raw | ConvertFrom-Json
        if ($metadata.Type -cnotin @('Audit', 'AuditAndSet') -or $metadata.Version -notmatch '^\d+\.\d+\.\d+$') {
            throw 'Package metadata must contain a valid Type and Version. Re-export the bundle from the builder.'
        }
        if ($PSBoundParameters.ContainsKey('Mode') -and $Mode -cne $metadata.Type) {
            throw '-Mode conflicts with package metadata. Re-export the bundle with the intended mode.'
        }
        $Mode = $metadata.Type
        $packageVersion = $metadata.Version
    }

    # ─── Auto-detect mode from config JSON or policy.json (if -Mode not explicitly passed) ───
    if (-not $PSBoundParameters.ContainsKey('Mode') -and -not (Test-Path -LiteralPath $metadataPath)) {
        $modeDetected = $false

        # 1. Try config JSON files (tool output)
        $configJsonFiles = Get-ChildItem -Path $configDir -Filter '*.json' | Where-Object { $_.Name -ne 'policy.json' }
        foreach ($cjf in $configJsonFiles) {
            try {
                $cjContent = Get-Content $cjf.FullName -Raw | ConvertFrom-Json
                if ($cjContent.mode) {
                    if ($cjContent.mode -eq 'AuditAndSet') { $Mode = 'AuditAndSet' }
                    elseif ($cjContent.mode -eq 'Audit') { $Mode = 'Audit' }
                    Write-Host "   Auto-detected mode from $($cjf.Name): $Mode" -ForegroundColor Gray
                    $modeDetected = $true
                    break
                }
            } catch {
                throw "Invalid config JSON in '$($cjf.Name)': $($_.Exception.Message)"
            }
        }

        # 2. Fallback: infer from policy.json effect
        if (-not $modeDetected) {
            $policyJsonCheck = Join-Path $configDir 'policy.json'
            if (Test-Path $policyJsonCheck) {
                $pjRaw = Get-Content $policyJsonCheck -Raw
                if ($pjRaw -match 'deployIfNotExists') {
                    $Mode = 'AuditAndSet'
                    Write-Host "   Auto-detected mode from policy.json effect: $Mode" -ForegroundColor Gray
                }
            }
        }
    }

    Write-Host ''
    Write-Host "╔══════════════════════════════════════════════════════════════╗" -ForegroundColor Cyan
    Write-Host "║  Azure Machine Configuration — Build & Deploy                ║" -ForegroundColor Cyan
    Write-Host "╚══════════════════════════════════════════════════════════════╝" -ForegroundColor Cyan
    Write-Host "  Config:   $configName" -ForegroundColor Gray
    Write-Host "  Mode:     $Mode" -ForegroundColor Gray
    Write-Host ''

    # ─── Detect required modules from MOF ─────────────────────────────────────
    Write-Host '[DETECT] Detecting required DSC modules from MOF...' -ForegroundColor Cyan
    $mofContent = Get-Content $mofFile.FullName -Raw

    $moduleRegex = [regex]'ModuleName\s*=\s*"(?<name>[^"]+)"\s*;\s*ModuleVersion\s*=\s*"(?<ver>[^"]+)"'
    $mofMatches = $moduleRegex.Matches($mofContent)
    $requiredModules = @{}

    foreach ($match in $mofMatches) {
        $name = $match.Groups['name'].Value
        $ver = $match.Groups['ver'].Value
        if (-not $requiredModules.ContainsKey($name)) {
            $requiredModules[$name] = $ver
        }
    }

    if ($requiredModules.Count -eq 0) {
        Write-Error "No DSC modules found in MOF. The MOF may be malformed."
        exit 1
    }

    Write-Host "   Found $($requiredModules.Count) module(s): $($requiredModules.Keys -join ', ')" -ForegroundColor Gray

    # ─── Install modules ──────────────────────────────────────────────────────
    Write-Host '[INSTALL] Installing required modules...' -ForegroundColor Cyan

    if (-not (Get-Module -ListAvailable -Name GuestConfiguration)) {
        Install-Module -Name GuestConfiguration -Force -Scope CurrentUser -ErrorAction Stop
    } else {
        Write-Host '   GuestConfiguration already installed' -ForegroundColor Gray
    }

    foreach ($modName in $requiredModules.Keys) {
        $modVer = $requiredModules[$modName]
        $existing = Get-Module -ListAvailable -Name $modName | Where-Object { $_.Version.ToString() -eq $modVer }
        if ($existing) {
            Write-Host "   $modName v$modVer already installed" -ForegroundColor Gray
        } else {
            Write-Host "   Installing $modName v$modVer..." -ForegroundColor Gray
            Install-Module -Name $modName -RequiredVersion $modVer -Force -Scope CurrentUser -ErrorAction Stop
        }
    }

    # ─── Create package ──────────────────────────────────────────────────────
    $outputDir = Join-Path $configDir 'output'
    $packageType = if ($Mode -eq 'AuditAndSet') { 'AuditAndSet' } else { 'Audit' }
    Write-Host "[BUILD] Creating MC package (Type: $packageType)..." -ForegroundColor Cyan

    $package = New-GuestConfigurationPackage `
        -Name $configName `
        -Configuration $mofFile.FullName `
        -Path $outputDir `
        -Type $packageType `
        -Version $packageVersion `
        -Force

    # ─── Fix module structure (Azure GC requires versioned paths) ─────────────
    Write-Host '[CHECK] Checking ZIP module structure...' -ForegroundColor Cyan
    Add-Type -AssemblyName System.IO.Compression.FileSystem -ErrorAction SilentlyContinue

    $zipPath = $package.Path
    $needsRepair = $false

    $zip = [System.IO.Compression.ZipFile]::OpenRead($zipPath)
    $entries = $zip.Entries | ForEach-Object { $_.FullName }
    $zip.Dispose()

    foreach ($modName in $requiredModules.Keys) {
        $modVer = $requiredModules[$modName]
        $hasVersioned = $entries | Where-Object { $_ -like "Modules/$modName/$modVer/*" }
        if (-not $hasVersioned) {
            $hasFlat = $entries | Where-Object { $_ -like "Modules/$modName/*" }
            if ($hasFlat) {
                Write-Host "   [WARN] $modName is flat — needs versioned subfolder" -ForegroundColor Yellow
                $needsRepair = $true
            }
        }
    }

    if ($needsRepair) {
        Write-Host '   Repackaging with versioned module paths...' -ForegroundColor Yellow
        $tmpStage = Join-Path ([System.IO.Path]::GetTempPath()) "zip-repair-$(Get-Random)"
        [System.IO.Compression.ZipFile]::ExtractToDirectory($zipPath, $tmpStage)

        foreach ($modName in $requiredModules.Keys) {
            $modVer = $requiredModules[$modName]
            $flatDir = Join-Path $tmpStage "Modules/$modName"
            $versionedDir = Join-Path $tmpStage "Modules/$modName/$modVer"
            if ((Test-Path $flatDir) -and -not (Test-Path $versionedDir)) {
                $tempMove = Join-Path ([System.IO.Path]::GetTempPath()) "mod-move-$(Get-Random)"
                Move-Item $flatDir $tempMove
                New-Item -ItemType Directory -Path $flatDir -Force | Out-Null
                Move-Item $tempMove $versionedDir
            }
        }

        Remove-Item $zipPath -Force
        [System.IO.Compression.ZipFile]::CreateFromDirectory($tmpStage, $zipPath)
        Remove-Item $tmpStage -Recurse -Force
        Write-Host '   [OK] Module paths fixed' -ForegroundColor Green
    } else {
        Write-Host '   [OK] Module structure OK' -ForegroundColor Green
    }

    $PackagePath = $zipPath
}

# ─── Validate ZIP path ───────────────────────────────────────────────────────

if (-not (Test-Path $PackagePath)) {
    Write-Error "Package not found: $PackagePath"
    exit 1
}

$packageFile = Get-Item $PackagePath
if (-not $configName) { $configName = $packageFile.BaseName }
$hash = (Get-FileHash -Path $PackagePath -Algorithm SHA256).Hash

# ─── Auto-detect mode from sibling policy.json when using -PackagePath ────────
if (-not $PSBoundParameters.ContainsKey('Mode') -and -not $ConfigPath) {
    $searchDirs = @(
        (Split-Path $PackagePath -Parent),
        (Split-Path (Split-Path $PackagePath -Parent) -Parent)
    )
    foreach ($dir in $searchDirs) {
        $pjCheck = Join-Path $dir 'policy.json'
        if (Test-Path $pjCheck) {
            $pjRaw = Get-Content $pjCheck -Raw
            if ($pjRaw -match 'deployIfNotExists') {
                $Mode = 'AuditAndSet'
                Write-Host "   Auto-detected mode from policy.json: $Mode" -ForegroundColor Gray
            }
            break
        }
    }
}

if (-not $ConfigPath) {
    Write-Host ''
    Write-Host "╔══════════════════════════════════════════════════════════════╗" -ForegroundColor Cyan
    Write-Host "║  Azure Machine Configuration — Deploy                        ║" -ForegroundColor Cyan
    Write-Host "╚══════════════════════════════════════════════════════════════╝" -ForegroundColor Cyan
    Write-Host "  Package:  $configName" -ForegroundColor Gray
    Write-Host "  Mode:     $Mode" -ForegroundColor Gray
    Write-Host "  Hash:     $($hash.Substring(0,16))..." -ForegroundColor Gray
    Write-Host ''
}

# ─── Azure Login ──────────────────────────────────────────────────────────────

if (-not $SkipLogin) {
    $context = Get-AzContext -ErrorAction SilentlyContinue
    if (-not $context) {
        Write-Host '[AUTH] Connecting to Azure...' -ForegroundColor Cyan
        Connect-AzAccount
        $context = Get-AzContext
        if (-not $context -or -not $context.Subscription.Id) {
            throw 'No Azure subscription context found. Run Connect-AzAccount and select a subscription.'
        }
    } else {
        Write-Host "[AUTH] Using existing Azure context: $($context.Account.Id)" -ForegroundColor Gray
    }
}

if ($SubscriptionId) {
    Write-Host "   Setting subscription: $SubscriptionId" -ForegroundColor Gray
    Set-AzContext -SubscriptionId $SubscriptionId | Out-Null
}

$context = Get-AzContext
$subId = $context.Subscription.Id
Write-Host "   Subscription: $($context.Subscription.Name) ($subId)" -ForegroundColor Gray
Write-Host ''

# ─── Storage Account ─────────────────────────────────────────────────────────

$storageRg = if ($StorageResourceGroup) { $StorageResourceGroup } elseif ($ResourceGroupName) { $ResourceGroupName } else { "MC-Packages-$($subId.Substring(0,8))" }
$useExistingAccount = $StorageAccountName -and $StorageAuthMode -eq 'UserDelegation'

if (-not $StorageAccountName) {
    $StorageAccountName = "mcpkgs$($subId.Substring(0,8).ToLower() -replace '[^a-z0-9]','')"
    if ($StorageAccountName.Length -gt 24) { $StorageAccountName = $StorageAccountName.Substring(0, 24) }
}

Write-Host '[STORAGE] Setting up storage...' -ForegroundColor Cyan

$storage = $null
if ($useExistingAccount) {
    Write-Host "   Using existing storage with Microsoft Entra ID: $StorageAccountName" -ForegroundColor Gray
} elseif ($StorageResourceGroup -or $ResourceGroupName) {
    $storage = Get-AzStorageAccount -ResourceGroupName $storageRg -ErrorAction Stop |
        Where-Object { $_.StorageAccountName -eq $StorageAccountName }
} else {
    $storage = Get-AzStorageAccount -ErrorAction Stop | Where-Object { $_.StorageAccountName -eq $StorageAccountName } | Select-Object -First 1
}
if (-not $storage -and -not $useExistingAccount) {
    $rg = Get-AzResourceGroup -Name $storageRg -ErrorAction SilentlyContinue
    if (-not $rg) {
        Write-Host "   Creating resource group: $storageRg" -ForegroundColor Gray
        New-AzResourceGroup -Name $storageRg -Location $Location | Out-Null
    }
    Write-Host "   Creating storage account: $StorageAccountName" -ForegroundColor Gray
    $storage = New-AzStorageAccount `
        -ResourceGroupName $storageRg `
        -Name $StorageAccountName `
        -Location $Location `
        -SkuName Standard_LRS `
        -Kind StorageV2 `
        -AllowBlobPublicAccess $false
} else {
    Write-Host "   Using existing storage: $StorageAccountName (in $($storage.ResourceGroupName))" -ForegroundColor Gray
}

if ($StorageAuthMode -eq 'UserDelegation') {
    $storageCtx = New-AzStorageContext -StorageAccountName $StorageAccountName -UseConnectedAccount -Environment $context.Environment.Name
} else {
    if ($storage.AllowSharedKeyAccess -eq $false) {
        throw 'This storage account disables Shared Key access. Use -StorageAuthMode UserDelegation.'
    }
    Write-Warning 'SharedKey mode explicitly uses an account key. Prefer UserDelegation where possible.'
    $storageKey = (Get-AzStorageAccountKey -ResourceGroupName $storage.ResourceGroupName -Name $StorageAccountName -ErrorAction Stop)[0].Value
    $storageCtx = New-AzStorageContext -StorageAccountName $StorageAccountName -StorageAccountKey $storageKey -Environment $context.Environment.Name
}

try {
    $container = Get-AzStorageContainer -Context $storageCtx -ErrorAction Stop | Where-Object { $_.Name -eq $ContainerName }
} catch {
    throw 'Cannot access blob storage. UserDelegation requires Storage Blob Data Contributor at storage-account scope (including delegation-key permission) and network access. No Shared Key fallback was attempted.'
}
if (-not $container) {
    Write-Host "   Creating container: $ContainerName" -ForegroundColor Gray
    New-AzStorageContainer -Name $ContainerName -Context $storageCtx -Permission Off | Out-Null
}

# ─── Upload Package ──────────────────────────────────────────────────────────

$blobName = "$configName-$($hash.Substring(0,8).ToLower()).zip"
Write-Host "   Uploading $blobName..." -ForegroundColor Gray

Set-AzStorageBlobContent `
    -File $PackagePath `
    -Container $ContainerName `
    -Blob $blobName `
    -Context $storageCtx `
    -Force | Out-Null

$sasStart = (Get-Date).ToUniversalTime().AddMinutes(-5)
$sasExpiry = (Get-Date).ToUniversalTime().AddDays($SasExpiryDays)
$sasToken = New-AzStorageBlobSASToken `
    -Container $ContainerName `
    -Blob $blobName `
    -Permission r `
    -Protocol HttpsOnly `
    -StartTime $sasStart `
    -ExpiryTime $sasExpiry `
    -Context $storageCtx `
    -FullUri

Write-Host "   [OK] Uploaded with SAS URL (expires $($sasExpiry.ToString('yyyy-MM-dd')))" -ForegroundColor Green
Write-Warning "Renew the SAS and re-run this script before $($sasExpiry.ToString('yyyy-MM-dd HH:mm')) UTC. Expired URLs prevent package downloads."
Write-Host ''

# ─── Create Policy Definition ────────────────────────────────────────────────

Write-Host '[POLICY] Creating policy definition...' -ForegroundColor Cyan

$policyName = "MC-$configName"
$displayName = "Machine Configuration: $configName"

# Check for policy.json next to the package or in the config folder
$policyJsonPath = $null
if ($ConfigPath) {
    $policyJsonPath = Join-Path (Resolve-Path $ConfigPath) 'policy.json'
}
if (-not $policyJsonPath -or -not (Test-Path $policyJsonPath)) {
    $packageDir = Split-Path (Resolve-Path $PackagePath) -Parent
    $policyJsonPath = Join-Path $packageDir 'policy.json'
    if (-not (Test-Path $policyJsonPath)) {
        $parentDir = Split-Path $packageDir -Parent
        if ($parentDir) {
            $policyJsonPath = Join-Path $parentDir 'policy.json'
        }
    }
}

if (Test-Path $policyJsonPath) {
    Write-Host "   Using policy.json from: $policyJsonPath" -ForegroundColor Gray
    $policyContent = Get-Content $policyJsonPath -Raw
    $policyContent = $policyContent.Replace('"{{contentUri}}"', (ConvertTo-Json -InputObject $sasToken -Compress))
    $policyContent = $policyContent.Replace('"{{contentHash}}"', (ConvertTo-Json -InputObject $hash -Compress))
    $null = $policyContent | ConvertFrom-Json

    # Upsert in place so existing assignments keep their definition ID.
    $policyDef = New-AzPolicyDefinition `
        -Name $policyName `
        -DisplayName $displayName `
        -Policy $policyContent `
        -SubscriptionId $subId `
        -Mode 'Indexed'

} else {
    Write-Host "   [WARN] No policy.json found — policy.json is required to create the definition." -ForegroundColor Yellow
    Write-Host "   Place a policy.json alongside the package and re-run, or use -ConfigPath instead." -ForegroundColor Yellow
    exit 1
}

Write-Host "   [OK] Policy definition created: $($policyDef.Name)" -ForegroundColor Green
Write-Host "   ID: $($policyDef.Id)" -ForegroundColor Gray
Write-Host ''

# ─── Summary ─────────────────────────────────────────────────────────────────

Write-Host "╔══════════════════════════════════════════════════════════════╗" -ForegroundColor Green
Write-Host "║  Done                                                        ║" -ForegroundColor Green
Write-Host "╚══════════════════════════════════════════════════════════════╝" -ForegroundColor Green
Write-Host ''
Write-Host "  Package:           $configName" -ForegroundColor White
Write-Host "  Hash:              $($hash.Substring(0,16))..." -ForegroundColor White
Write-Host "  Storage:           $StorageAccountName/$ContainerName/$blobName" -ForegroundColor White
Write-Host "  Policy Definition: $($policyDef.Id)" -ForegroundColor White
Write-Host ''
Write-Host '  Policy definition created. Assign it from Azure Portal.' -ForegroundColor Green
Write-Host ''
Write-Host '  Or assign via PowerShell:'
Write-Host "     `$def = Get-AzPolicyDefinition -Name '$policyName'" -ForegroundColor Gray
if ($Mode -eq 'AuditAndSet') {
    Write-Host "     `$assignment = New-AzPolicyAssignment -Name 'MyAssignment' -PolicyDefinition `$def -Scope '/subscriptions/$subId' -Location '$Location' -IdentityType SystemAssigned" -ForegroundColor Gray
    Write-Host "     New-AzRoleAssignment -ObjectId `$assignment.Identity.PrincipalId -RoleDefinitionId '088ab73d-1256-47ae-bea9-9de8e7131f31' -Scope '/subscriptions/$subId'" -ForegroundColor Gray
    Write-Host '     # Allow identity/RBAC propagation before starting remediation.' -ForegroundColor Gray
    Write-Host "     Start-AzPolicyRemediation -Name '$configName-remediation' -PolicyAssignmentId `$assignment.Id" -ForegroundColor Gray
} else {
    Write-Host "     New-AzPolicyAssignment -Name 'MyAssignment' -PolicyDefinition `$def -Scope '/subscriptions/$subId'" -ForegroundColor Gray
}
Write-Host ''
Write-Host '  VM Prerequisites — assign this built-in initiative at subscription level:' -ForegroundColor Yellow
Write-Host '     "Deploy prerequisites to enable Guest Configuration policies on virtual machines"' -ForegroundColor Yellow
Write-Host '     Initiative ID: 12794019-7a00-42cf-95c2-882eed337cc8' -ForegroundColor Yellow
Write-Host ''
