# deploy.ps1 — Build and deploy an Azure Machine Configuration package to Azure
# Generated by Azure Machine Configuration Builder
#
# Usage:
#   .\deploy.ps1 -ConfigPath .\WindowsServiceMonitoring\ [-Scope ResourceGroup -ResourceGroupName MyRG]
#   .\deploy.ps1 -PackagePath .\output\MyConfig.zip [-Scope VM -ResourceGroupName MyRG -VMName MyVM]
#
# -ConfigPath  → points to the extracted config folder (contains .mof + policy.json)
#                Builds the ZIP automatically (installs modules, packages, fixes structure)
# -PackagePath → points to a pre-built .zip file (skips the build step)
#
# Scope options:
#   -Scope Subscription    → assigns policy to the entire subscription (default)
#   -Scope ResourceGroup   → assigns policy to the specified resource group
#   -Scope VM              → assigns policy to a specific VM (-VMName required)

#Requires -Version 7.0
#Requires -Modules Az.Accounts, Az.Storage, Az.Resources

[CmdletBinding()]
param(
    [Parameter(ParameterSetName='FromConfig')]
    [string]$ConfigPath,

    [Parameter(ParameterSetName='FromZip')]
    [string]$PackagePath,

    [string]$SubscriptionId,

    [string]$ResourceGroupName,

    [ValidateSet('Subscription', 'ResourceGroup', 'VM')]
    [string]$Scope = 'Subscription',

    [string]$VMName,

    [string]$StorageAccountName,

    [string]$StorageResourceGroup,

    [string]$ContainerName = 'guestconfiguration',

    [string]$Location = 'uksouth',

    [ValidateSet('Audit', 'AuditAndSet')]
    [string]$Mode = 'Audit',

    [ValidateSet('Windows', 'Linux', 'Auto')]
    [string]$Platform = 'Auto',

    [switch]$SkipLogin,

    [switch]$SkipTest
)

$ErrorActionPreference = 'Stop'

# ─── Validate inputs ─────────────────────────────────────────────────────────

if (-not $ConfigPath -and -not $PackagePath) {
    Write-Error "Specify either -ConfigPath (folder with .mof) or -PackagePath (pre-built .zip)"
    exit 1
}

if ($ConfigPath -and $PackagePath) {
    Write-Error "Specify only one of -ConfigPath or -PackagePath, not both"
    exit 1
}

if ($Scope -eq 'ResourceGroup' -and -not $ResourceGroupName) {
    Write-Error "-ResourceGroupName is required when -Scope is ResourceGroup"
    exit 1
}

if ($Scope -eq 'VM' -and (-not $ResourceGroupName -or -not $VMName)) {
    Write-Error "-ResourceGroupName and -VMName are required when -Scope is VM"
    exit 1
}

# ─── Build Package (if -ConfigPath) ──────────────────────────────────────────

if ($ConfigPath) {
    if (-not (Test-Path $ConfigPath -PathType Container)) {
        Write-Error "Config folder not found: $ConfigPath"
        exit 1
    }

    $configDir = Resolve-Path $ConfigPath
    $mofFile = Get-ChildItem -Path $configDir -Filter '*.mof' | Select-Object -First 1
    if (-not $mofFile) {
        Write-Error "No .mof file found in $configDir"
        exit 1
    }

    $configName = $mofFile.BaseName

    Write-Host ''
    Write-Host "╔══════════════════════════════════════════════════════════════╗" -ForegroundColor Cyan
    Write-Host "║  Azure Machine Configuration — Build & Deploy                ║" -ForegroundColor Cyan
    Write-Host "╚══════════════════════════════════════════════════════════════╝" -ForegroundColor Cyan
    Write-Host "  Config:   $configName" -ForegroundColor Gray
    Write-Host "  Mode:     $Mode" -ForegroundColor Gray
    Write-Host "  Scope:    $Scope" -ForegroundColor Gray
    Write-Host ''

    # ─── Detect required modules from MOF ─────────────────────────────────────
    Write-Host '🔍 Detecting required DSC modules from MOF...' -ForegroundColor Cyan
    $mofContent = Get-Content $mofFile.FullName -Raw

    $moduleRegex = [regex]'ModuleName\s*=\s*"(?<name>[^"]+)"\s*;\s*ModuleVersion\s*=\s*"(?<ver>[^"]+)"'
    $mofMatches = $moduleRegex.Matches($mofContent)
    $requiredModules = @{}

    foreach ($match in $mofMatches) {
        $name = $match.Groups['name'].Value
        $ver = $match.Groups['ver'].Value
        if (-not $requiredModules.ContainsKey($name)) {
            $requiredModules[$name] = $ver
        }
    }

    if ($requiredModules.Count -eq 0) {
        Write-Error "No DSC modules found in MOF. The MOF may be malformed."
        exit 1
    }

    Write-Host "   Found $($requiredModules.Count) module(s): $($requiredModules.Keys -join ', ')" -ForegroundColor Gray

    # ─── Install modules ──────────────────────────────────────────────────────
    Write-Host '📦 Installing required modules...' -ForegroundColor Cyan

    if (-not (Get-Module -ListAvailable -Name GuestConfiguration)) {
        Install-Module -Name GuestConfiguration -Force -Scope CurrentUser -ErrorAction Stop
    } else {
        Write-Host '   GuestConfiguration already installed' -ForegroundColor Gray
    }

    foreach ($modName in $requiredModules.Keys) {
        $modVer = $requiredModules[$modName]
        $existing = Get-Module -ListAvailable -Name $modName | Where-Object { $_.Version.ToString() -eq $modVer }
        if ($existing) {
            Write-Host "   $modName v$modVer already installed" -ForegroundColor Gray
        } else {
            Write-Host "   Installing $modName v$modVer..." -ForegroundColor Gray
            Install-Module -Name $modName -RequiredVersion $modVer -Force -Scope CurrentUser -ErrorAction Stop
        }
    }

    # ─── Create package ──────────────────────────────────────────────────────
    $outputDir = Join-Path $configDir 'output'
    $packageType = if ($Mode -eq 'AuditAndSet') { 'AuditAndSet' } else { 'Audit' }
    Write-Host "🔨 Creating MC package (Type: $packageType)..." -ForegroundColor Cyan

    $package = New-GuestConfigurationPackage `
        -Name $configName `
        -Configuration $mofFile.FullName `
        -Path $outputDir `
        -Type $packageType `
        -Force

    # ─── Fix module structure (Azure GC requires versioned paths) ─────────────
    Write-Host '🔧 Checking ZIP module structure...' -ForegroundColor Cyan
    Add-Type -AssemblyName System.IO.Compression.FileSystem -ErrorAction SilentlyContinue

    $zipPath = $package.Path
    $needsRepair = $false

    $zip = [System.IO.Compression.ZipFile]::OpenRead($zipPath)
    $entries = $zip.Entries | ForEach-Object { $_.FullName }
    $zip.Dispose()

    foreach ($modName in $requiredModules.Keys) {
        $modVer = $requiredModules[$modName]
        $hasVersioned = $entries | Where-Object { $_ -like "Modules/$modName/$modVer/*" }
        if (-not $hasVersioned) {
            $hasFlat = $entries | Where-Object { $_ -like "Modules/$modName/*" }
            if ($hasFlat) {
                Write-Host "   ⚠️  $modName is flat — needs versioned subfolder" -ForegroundColor Yellow
                $needsRepair = $true
            }
        }
    }

    if ($needsRepair) {
        Write-Host '   Repackaging with versioned module paths...' -ForegroundColor Yellow
        $tmpStage = Join-Path ([System.IO.Path]::GetTempPath()) "zip-repair-$(Get-Random)"
        [System.IO.Compression.ZipFile]::ExtractToDirectory($zipPath, $tmpStage)

        foreach ($modName in $requiredModules.Keys) {
            $modVer = $requiredModules[$modName]
            $flatDir = Join-Path $tmpStage "Modules/$modName"
            $versionedDir = Join-Path $tmpStage "Modules/$modName/$modVer"
            if ((Test-Path $flatDir) -and -not (Test-Path $versionedDir)) {
                $tempMove = Join-Path ([System.IO.Path]::GetTempPath()) "mod-move-$(Get-Random)"
                Move-Item $flatDir $tempMove
                New-Item -ItemType Directory -Path $flatDir -Force | Out-Null
                Move-Item $tempMove $versionedDir
            }
        }

        Remove-Item $zipPath -Force
        [System.IO.Compression.ZipFile]::CreateFromDirectory($tmpStage, $zipPath)
        Remove-Item $tmpStage -Recurse -Force
        Write-Host '   ✅ Module paths fixed' -ForegroundColor Green
    } else {
        Write-Host '   ✅ Module structure OK' -ForegroundColor Green
    }

    $PackagePath = $zipPath

    # ─── Optional local compliance test ───────────────────────────────────────
    if (-not $SkipTest) {
        Write-Host '🧪 Running local compliance test...' -ForegroundColor Cyan
        $isWin = $PSVersionTable.PSVersion -and ($IsWindows -or $env:OS -eq 'Windows_NT')
        $isElevated = if ($isWin) {
            ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
        } else { $true }

        if (-not $isElevated) {
            Write-Host '   ⚠️  Skipping — requires Administrator on Windows' -ForegroundColor Yellow
        } else {
            try {
                $testCmd = if (Get-Command 'Test-GuestConfigurationPackage' -ErrorAction SilentlyContinue) {
                    'Test-GuestConfigurationPackage'
                } else {
                    'Get-GuestConfigurationPackageComplianceStatus'
                }
                $result = & $testCmd -Path $PackagePath
                Write-Host "   Status: $($result.complianceStatus)" -ForegroundColor $(if ($result.complianceStatus -eq $true -or $result.complianceStatus -eq 'Compliant') { 'Green' } else { 'Yellow' })
            } catch {
                Write-Host "   ⚠️  Local test failed: $($_.Exception.Message)" -ForegroundColor Yellow
            }
        }
        Write-Host ''
    }
}

# ─── Validate ZIP path ───────────────────────────────────────────────────────

if (-not (Test-Path $PackagePath)) {
    Write-Error "Package not found: $PackagePath"
    exit 1
}

$packageFile = Get-Item $PackagePath
if (-not $configName) { $configName = $packageFile.BaseName }
$hash = (Get-FileHash -Path $PackagePath -Algorithm SHA256).Hash

if (-not $ConfigPath) {
    Write-Host ''
    Write-Host "╔══════════════════════════════════════════════════════════════╗" -ForegroundColor Cyan
    Write-Host "║  Azure Machine Configuration — Deploy                       ║" -ForegroundColor Cyan
    Write-Host "╚══════════════════════════════════════════════════════════════╝" -ForegroundColor Cyan
    Write-Host "  Package:  $configName" -ForegroundColor Gray
    Write-Host "  Mode:     $Mode" -ForegroundColor Gray
    Write-Host "  Scope:    $Scope" -ForegroundColor Gray
    Write-Host "  Hash:     $($hash.Substring(0,16))..." -ForegroundColor Gray
    Write-Host ''
}

# ─── Azure Login ──────────────────────────────────────────────────────────────

if (-not $SkipLogin) {
    $context = Get-AzContext -ErrorAction SilentlyContinue
    if (-not $context) {
        Write-Host '🔑 Connecting to Azure...' -ForegroundColor Cyan
        Connect-AzAccount
        $context = Get-AzContext
    } else {
        Write-Host "🔑 Using existing Azure context: $($context.Account.Id)" -ForegroundColor Gray
    }
}

if ($SubscriptionId) {
    Write-Host "   Setting subscription: $SubscriptionId" -ForegroundColor Gray
    Set-AzContext -SubscriptionId $SubscriptionId | Out-Null
}

$context = Get-AzContext
$subId = $context.Subscription.Id
Write-Host "   Subscription: $($context.Subscription.Name) ($subId)" -ForegroundColor Gray
Write-Host ''

# ─── Storage Account ─────────────────────────────────────────────────────────

$storageRg = if ($StorageResourceGroup) { $StorageResourceGroup } elseif ($ResourceGroupName) { $ResourceGroupName } else { "MC-Packages-$($subId.Substring(0,8))" }

if (-not $StorageAccountName) {
    $StorageAccountName = "mcpkgs$($subId.Substring(0,8).ToLower() -replace '[^a-z0-9]','')"
    if ($StorageAccountName.Length -gt 24) { $StorageAccountName = $StorageAccountName.Substring(0, 24) }
}

Write-Host '📦 Setting up storage...' -ForegroundColor Cyan

# Search all RGs for existing storage account (names are globally unique)
$storage = Get-AzStorageAccount | Where-Object { $_.StorageAccountName -eq $StorageAccountName } | Select-Object -First 1
if (-not $storage) {
    $rg = Get-AzResourceGroup -Name $storageRg -ErrorAction SilentlyContinue
    if (-not $rg) {
        Write-Host "   Creating resource group: $storageRg" -ForegroundColor Gray
        New-AzResourceGroup -Name $storageRg -Location $Location | Out-Null
    }
    Write-Host "   Creating storage account: $StorageAccountName" -ForegroundColor Gray
    $storage = New-AzStorageAccount `
        -ResourceGroupName $storageRg `
        -Name $StorageAccountName `
        -Location $Location `
        -SkuName Standard_LRS `
        -Kind StorageV2 `
        -AllowBlobPublicAccess $false
} else {
    Write-Host "   Using existing storage: $StorageAccountName (in $($storage.ResourceGroupName))" -ForegroundColor Gray
}

$storageCtx = $storage.Context

$container = Get-AzStorageContainer -Name $ContainerName -Context $storageCtx -ErrorAction SilentlyContinue
if (-not $container) {
    Write-Host "   Creating container: $ContainerName" -ForegroundColor Gray
    New-AzStorageContainer -Name $ContainerName -Context $storageCtx -Permission Off | Out-Null
}

# ─── Upload Package ──────────────────────────────────────────────────────────

$blobName = "$configName-$($hash.Substring(0,8).ToLower()).zip"
Write-Host "   Uploading $blobName..." -ForegroundColor Gray

Set-AzStorageBlobContent `
    -File $PackagePath `
    -Container $ContainerName `
    -Blob $blobName `
    -Context $storageCtx `
    -Force | Out-Null

$sasExpiry = (Get-Date).AddYears(3)
$sasToken = New-AzStorageBlobSASToken `
    -Container $ContainerName `
    -Blob $blobName `
    -Permission r `
    -ExpiryTime $sasExpiry `
    -Context $storageCtx `
    -FullUri

Write-Host "   ✅ Uploaded with SAS URL (expires $($sasExpiry.ToString('yyyy-MM-dd')))" -ForegroundColor Green
Write-Host ''

# ─── Create Policy Definition ────────────────────────────────────────────────

Write-Host '📋 Creating policy definition...' -ForegroundColor Cyan

$policyName = "MC-$configName"
$displayName = "Machine Configuration: $configName"

# Auto-cleanup existing policy before redeploy
$existingAssignment = $null
try { $existingAssignment = Get-AzPolicyAssignment -Name "assign-$configName" } catch {}
if ($existingAssignment) {
    Write-Host "   🗑️  Removing existing assignment: assign-$configName" -ForegroundColor Yellow
    Remove-AzPolicyAssignment -Name "assign-$configName" -ErrorAction SilentlyContinue
    Start-Sleep -Seconds 5
}

$existingDef = $null
try { $existingDef = Get-AzPolicyDefinition -Name $policyName } catch {}
if ($existingDef) {
    Write-Host "   🗑️  Removing existing policy definition: $policyName" -ForegroundColor Yellow
    Remove-AzPolicyDefinition -Name $policyName -Force -ErrorAction SilentlyContinue
    Start-Sleep -Seconds 5
}

# Check for policy.json next to the package or in the config folder
$policyJsonPath = $null
if ($ConfigPath) {
    $policyJsonPath = Join-Path (Resolve-Path $ConfigPath) 'policy.json'
}
if (-not $policyJsonPath -or -not (Test-Path $policyJsonPath)) {
    $packageDir = Split-Path (Resolve-Path $PackagePath) -Parent
    $policyJsonPath = Join-Path $packageDir 'policy.json'
    if (-not (Test-Path $policyJsonPath)) {
        $parentDir = Split-Path $packageDir -Parent
        if ($parentDir) {
            $policyJsonPath = Join-Path $parentDir 'policy.json'
        }
    }
}

if (Test-Path $policyJsonPath) {
    Write-Host "   Using policy.json from: $policyJsonPath" -ForegroundColor Gray
    $policyContent = Get-Content $policyJsonPath -Raw
    $policyContent = $policyContent -replace '\{\{contentUri\}\}', $sasToken
    $policyContent = $policyContent -replace '\{\{contentHash\}\}', $hash

    $tempPolicy = Join-Path $env:TEMP "$configName-policy.json"
    $policyContent | Set-Content $tempPolicy -Encoding UTF8

    $policyDef = New-AzPolicyDefinition `
        -Name $policyName `
        -DisplayName $displayName `
        -Policy $tempPolicy `
        -Mode 'Indexed'

    Remove-Item $tempPolicy -ErrorAction SilentlyContinue
} else {
    Write-Host "   No policy.json found — building inline" -ForegroundColor Yellow

    # Auto-detect platform
    $detectedPlatform = $Platform
    if ($detectedPlatform -eq 'Auto') {
        try {
            Add-Type -AssemblyName System.IO.Compression.FileSystem
            $zip = [System.IO.Compression.ZipFile]::OpenRead((Resolve-Path $PackagePath))
            $mofEntry = $zip.Entries | Where-Object { $_.Name -like '*.mof' } | Select-Object -First 1
            if ($mofEntry) {
                $reader = [System.IO.StreamReader]::new($mofEntry.Open())
                $mofText = $reader.ReadToEnd()
                $reader.Close()
                if ($mofText -match 'nxtools') { $detectedPlatform = 'Linux' } else { $detectedPlatform = 'Windows' }
            } else { $detectedPlatform = 'Windows' }
            $zip.Dispose()
        } catch { $detectedPlatform = 'Windows' }
        Write-Host "   Auto-detected platform: $detectedPlatform" -ForegroundColor Gray
    }

    $isWindows = $detectedPlatform -eq 'Windows'
    $osTypeFilter = if ($isWindows) { 'Windows*' } else { 'Linux*' }
    $osProfileField = if ($isWindows) { 'windowsConfiguration' } else { 'linuxConfiguration' }

    $effect = if ($Mode -eq 'AuditAndSet') { 'deployIfNotExists' } else { 'auditIfNotExists' }

    $policyRule = @{
        'if' = @{
            'anyOf' = @(
                @{ 'allOf' = @(
                    @{ 'field' = 'type'; 'equals' = 'Microsoft.Compute/virtualMachines' }
                    @{ 'field' = 'Microsoft.Compute/virtualMachines/storageProfile.osDisk.osType'; 'like' = $osTypeFilter }
                    @{ 'field' = "Microsoft.Compute/virtualMachines/osProfile.$osProfileField"; 'exists' = 'true' }
                )}
                @{ 'allOf' = @(
                    @{ 'field' = 'type'; 'equals' = 'Microsoft.HybridCompute/machines' }
                    @{ 'field' = 'Microsoft.HybridCompute/machines/osName'; 'like' = $osTypeFilter }
                )}
            )
        }
        'then' = @{
            'effect' = $effect
            'details' = @{
                'type' = 'Microsoft.GuestConfiguration/guestConfigurationAssignments'
                'name' = $configName
                'existenceCondition' = @{
                    'allOf' = @(
                        @{ 'field' = 'Microsoft.GuestConfiguration/guestConfigurationAssignments/complianceStatus'; 'equals' = 'Compliant' }
                        @{ 'field' = 'Microsoft.GuestConfiguration/guestConfigurationAssignments/parameterHash'; 'equals' = '' }
                    )
                }
            }
        }
    }

    $policyObj = @{
        'properties' = @{
            'displayName' = $displayName
            'description' = "Machine Configuration policy for $configName (generated by MC Builder)"
            'policyType' = 'Custom'
            'mode' = 'Indexed'
            'policyRule' = $policyRule
            'metadata' = @{
                'category' = 'Guest Configuration'
                'guestConfiguration' = @{
                    'name' = $configName
                    'version' = '1.0.0'
                    'contentType' = 'Custom'
                    'contentUri' = $sasToken
                    'contentHash' = $hash
                    'configurationParameter' = @{}
                }
            }
        }
    }

    $tempPolicy = Join-Path $env:TEMP "$configName-policy.json"
    $policyObj | ConvertTo-Json -Depth 20 | Set-Content $tempPolicy -Encoding UTF8

    $policyDef = New-AzPolicyDefinition `
        -Name $policyName `
        -DisplayName $displayName `
        -Policy $tempPolicy `
        -Mode 'Indexed'

    Remove-Item $tempPolicy -ErrorAction SilentlyContinue
}

Write-Host "   ✅ Policy created: $($policyDef.Name)" -ForegroundColor Green
Write-Host "   ID: $($policyDef.PolicyDefinitionId)" -ForegroundColor Gray
Write-Host ''

# ─── Assign Policy ───────────────────────────────────────────────────────────

Write-Host '🎯 Assigning policy...' -ForegroundColor Cyan

$assignmentName = "assign-$configName"
if ($assignmentName.Length -gt 64) { $assignmentName = $assignmentName.Substring(0, 64) }

$assignParams = @{
    Name             = $assignmentName
    DisplayName      = "Assign: $displayName"
    PolicyDefinition = $policyDef
}

switch ($Scope) {
    'Subscription' {
        $assignParams.Scope = "/subscriptions/$subId"
        Write-Host "   Scope: Subscription ($($context.Subscription.Name))" -ForegroundColor Gray
    }
    'ResourceGroup' {
        $assignParams.Scope = "/subscriptions/$subId/resourceGroups/$ResourceGroupName"
        Write-Host "   Scope: Resource Group ($ResourceGroupName)" -ForegroundColor Gray
    }
    'VM' {
        $vm = Get-AzVM -ResourceGroupName $ResourceGroupName -Name $VMName -ErrorAction SilentlyContinue
        if ($vm) {
            $assignParams.Scope = $vm.Id
            Write-Host "   Scope: VM $VMName (Azure VM)" -ForegroundColor Gray
        } else {
            $arc = Get-AzConnectedMachine -ResourceGroupName $ResourceGroupName -Name $VMName -ErrorAction SilentlyContinue
            if ($arc) {
                $assignParams.Scope = $arc.Id
                Write-Host "   Scope: VM $VMName (Arc-enabled)" -ForegroundColor Gray
            } else {
                Write-Error "VM '$VMName' not found in '$ResourceGroupName' (checked Azure VMs and Arc machines)"
                exit 1
            }
        }
    }
}

if ($Mode -eq 'AuditAndSet') {
    $assignParams.Location = $Location
    $assignParams.IdentityType = 'SystemAssigned'
    Write-Host "   ℹ️  AuditAndSet mode — managed identity will be created" -ForegroundColor Gray
}

$assignment = New-AzPolicyAssignment @assignParams

Write-Host "   ✅ Policy assigned: $($assignment.Name)" -ForegroundColor Green
Write-Host ''

if ($Mode -eq 'AuditAndSet' -and $assignment.Identity.PrincipalId) {
    Write-Host '🔐 Granting remediation permissions...' -ForegroundColor Cyan
    $retries = 0
    while ($retries -lt 5) {
        try {
            New-AzRoleAssignment `
                -ObjectId $assignment.Identity.PrincipalId `
                -RoleDefinitionName 'Contributor' `
                -Scope $assignParams.Scope | Out-Null
            Write-Host "   ✅ Contributor role assigned to managed identity" -ForegroundColor Green
            break
        } catch {
            $retries++
            if ($retries -ge 5) {
                Write-Host "   ⚠️  Could not assign role — do it manually" -ForegroundColor Yellow
            } else { Start-Sleep -Seconds 5 }
        }
    }
    Write-Host ''
}

# ─── Trigger compliance scan ─────────────────────────────────────────────────

Write-Host '🔄 Triggering compliance scan...' -ForegroundColor Cyan
try {
    if ($ResourceGroupName) {
        Start-AzPolicyComplianceScan -ResourceGroupName $ResourceGroupName -AsJob | Out-Null
        Write-Host "   Scan started for RG: $ResourceGroupName" -ForegroundColor Gray
    } else {
        Start-AzPolicyComplianceScan -AsJob | Out-Null
        Write-Host "   Scan started for subscription" -ForegroundColor Gray
    }
} catch {
    Write-Host "   ⚠️  Could not trigger scan: $($_.Exception.Message)" -ForegroundColor Yellow
}
Write-Host ''

# ─── Summary ─────────────────────────────────────────────────────────────────

Write-Host "╔══════════════════════════════════════════════════════════════╗" -ForegroundColor Green
Write-Host "║  ✅ Deployment Complete                                      ║" -ForegroundColor Green
Write-Host "╚══════════════════════════════════════════════════════════════╝" -ForegroundColor Green
Write-Host ''
Write-Host "  Package:           $configName" -ForegroundColor White
Write-Host "  Hash:              $($hash.Substring(0,16))..." -ForegroundColor White
Write-Host "  Storage:           $StorageAccountName/$ContainerName/$blobName" -ForegroundColor White
Write-Host "  Policy Definition: $($policyDef.PolicyDefinitionId)" -ForegroundColor White
Write-Host "  Policy Assignment: $($assignment.Name)" -ForegroundColor White
Write-Host "  Scope:             $($assignParams.Scope)" -ForegroundColor White
Write-Host ''
Write-Host '  ⏱  The GC agent evaluates every 15 minutes. Check compliance:' -ForegroundColor Gray
Write-Host "     Get-AzPolicyState -PolicyAssignmentName '$assignmentName'" -ForegroundColor Gray
Write-Host ''
Write-Host '  ⚠️  VM Prerequisites — ensure this built-in initiative is assigned:' -ForegroundColor Yellow
Write-Host '     "Deploy prerequisites to enable Guest Configuration policies on VMs"' -ForegroundColor Yellow
Write-Host '     Initiative ID: 12794019-7a00-42cf-95c2-882eed337cc8' -ForegroundColor Yellow
Write-Host ''
