# deploy.ps1 — Deploy an Azure Machine Configuration package to Azure
# Generated by Azure Machine Configuration Builder
#
# Usage:
#   .\deploy.ps1 -PackagePath .\output\MyConfig.zip [-SubscriptionId <id>] [-ResourceGroupName <rg>] [-Scope <scope>]
#
# Scope options:
#   -Scope Subscription    → assigns policy to the entire subscription (default)
#   -Scope ResourceGroup   → assigns policy to the specified resource group
#   -Scope VM              → assigns policy to a specific VM (-VMName required)
#
# What this does:
#   1. Connects to Azure (interactive login or existing context)
#   2. Creates a storage account + container (or uses existing)
#   3. Uploads the package ZIP and generates a SAS URL
#   4. Creates an Azure Policy definition with the correct contentUri + contentHash
#   5. Assigns the policy to your chosen scope

#Requires -Version 7.0
#Requires -Modules Az.Accounts, Az.Storage, Az.Resources

[CmdletBinding()]
param(
    [Parameter(Mandatory)]
    [string]$PackagePath,

    [string]$SubscriptionId,

    [string]$ResourceGroupName,

    [ValidateSet('Subscription', 'ResourceGroup', 'VM')]
    [string]$Scope = 'Subscription',

    [string]$VMName,

    [string]$StorageAccountName,

    [string]$StorageResourceGroup,

    [string]$ContainerName = 'guestconfiguration',

    [string]$Location = 'uksouth',

    [ValidateSet('Audit', 'AuditAndSet')]
    [string]$Mode = 'Audit',

    [switch]$SkipLogin
)

$ErrorActionPreference = 'Stop'

# ─── Validate inputs ─────────────────────────────────────────────────────────

if (-not (Test-Path $PackagePath)) {
    Write-Error "Package not found: $PackagePath"
    exit 1
}

if ($Scope -eq 'ResourceGroup' -and -not $ResourceGroupName) {
    Write-Error "-ResourceGroupName is required when -Scope is ResourceGroup"
    exit 1
}

if ($Scope -eq 'VM' -and (-not $ResourceGroupName -or -not $VMName)) {
    Write-Error "-ResourceGroupName and -VMName are required when -Scope is VM"
    exit 1
}

$packageFile = Get-Item $PackagePath
$configName = $packageFile.BaseName
$hash = (Get-FileHash -Path $PackagePath -Algorithm SHA256).Hash

Write-Host ''
Write-Host "╔══════════════════════════════════════════════════════════════╗" -ForegroundColor Cyan
Write-Host "║  Azure Machine Configuration — Deploy                       ║" -ForegroundColor Cyan
Write-Host "╚══════════════════════════════════════════════════════════════╝" -ForegroundColor Cyan
Write-Host "  Package:  $configName" -ForegroundColor Gray
Write-Host "  Mode:     $Mode" -ForegroundColor Gray
Write-Host "  Scope:    $Scope" -ForegroundColor Gray
Write-Host "  Hash:     $($hash.Substring(0,16))..." -ForegroundColor Gray
Write-Host ''

# ─── Azure Login ──────────────────────────────────────────────────────────────

if (-not $SkipLogin) {
    $context = Get-AzContext -ErrorAction SilentlyContinue
    if (-not $context) {
        Write-Host '🔑 Connecting to Azure...' -ForegroundColor Cyan
        Connect-AzAccount
        $context = Get-AzContext
    } else {
        Write-Host "🔑 Using existing Azure context: $($context.Account.Id)" -ForegroundColor Gray
    }
}

if ($SubscriptionId) {
    Write-Host "   Setting subscription: $SubscriptionId" -ForegroundColor Gray
    Set-AzContext -SubscriptionId $SubscriptionId | Out-Null
}

$context = Get-AzContext
$subId = $context.Subscription.Id
Write-Host "   Subscription: $($context.Subscription.Name) ($subId)" -ForegroundColor Gray
Write-Host ''

# ─── Storage Account ─────────────────────────────────────────────────────────

$storageRg = if ($StorageResourceGroup) { $StorageResourceGroup } elseif ($ResourceGroupName) { $ResourceGroupName } else { "MC-Packages-$($subId.Substring(0,8))" }

# Auto-generate storage account name if not provided
if (-not $StorageAccountName) {
    $StorageAccountName = "mcpkgs$($subId.Substring(0,8).ToLower() -replace '[^a-z0-9]','')"
    # Storage account names: 3-24 chars, lowercase+numbers only
    if ($StorageAccountName.Length -gt 24) { $StorageAccountName = $StorageAccountName.Substring(0, 24) }
}

Write-Host '📦 Setting up storage...' -ForegroundColor Cyan

# Create resource group if needed
$rg = Get-AzResourceGroup -Name $storageRg -ErrorAction SilentlyContinue
if (-not $rg) {
    Write-Host "   Creating resource group: $storageRg" -ForegroundColor Gray
    New-AzResourceGroup -Name $storageRg -Location $Location | Out-Null
}

# Create storage account if needed
$storage = Get-AzStorageAccount -ResourceGroupName $storageRg -Name $StorageAccountName -ErrorAction SilentlyContinue
if (-not $storage) {
    Write-Host "   Creating storage account: $StorageAccountName" -ForegroundColor Gray
    $storage = New-AzStorageAccount `
        -ResourceGroupName $storageRg `
        -Name $StorageAccountName `
        -Location $Location `
        -SkuName Standard_LRS `
        -Kind StorageV2 `
        -AllowBlobPublicAccess $false
} else {
    Write-Host "   Using existing storage: $StorageAccountName" -ForegroundColor Gray
}

$storageCtx = $storage.Context

# Create container if needed
$container = Get-AzStorageContainer -Name $ContainerName -Context $storageCtx -ErrorAction SilentlyContinue
if (-not $container) {
    Write-Host "   Creating container: $ContainerName" -ForegroundColor Gray
    New-AzStorageContainer -Name $ContainerName -Context $storageCtx -Permission Off | Out-Null
}

# ─── Upload Package ──────────────────────────────────────────────────────────

$blobName = "$configName.zip"
Write-Host "   Uploading $blobName..." -ForegroundColor Gray

Set-AzStorageBlobContent `
    -File $PackagePath `
    -Container $ContainerName `
    -Blob $blobName `
    -Context $storageCtx `
    -Force | Out-Null

# Generate SAS token (valid for 3 years)
$sasExpiry = (Get-Date).AddYears(3)
$sasToken = New-AzStorageBlobSASToken `
    -Container $ContainerName `
    -Blob $blobName `
    -Permission r `
    -ExpiryTime $sasExpiry `
    -Context $storageCtx `
    -FullUri

Write-Host "   ✅ Uploaded with SAS URL (expires $($sasExpiry.ToString('yyyy-MM-dd')))" -ForegroundColor Green
Write-Host ''

# ─── Create Policy Definition ────────────────────────────────────────────────

Write-Host '📋 Creating policy definition...' -ForegroundColor Cyan

$policyName = "MC-$configName"
$displayName = "Machine Configuration: $configName"

# Check for policy.json next to the package or in parent directory
$packageDir = Split-Path (Resolve-Path $PackagePath) -Parent
$policyJsonPath = Join-Path $packageDir 'policy.json'
if (-not (Test-Path $policyJsonPath)) {
    $parentDir = Split-Path $packageDir -Parent
    if ($parentDir) {
        $policyJsonPath = Join-Path $parentDir 'policy.json'
    }
}

if (Test-Path $policyJsonPath) {
    Write-Host "   Using policy.json from: $policyJsonPath" -ForegroundColor Gray
    $policyContent = Get-Content $policyJsonPath -Raw
    # Replace placeholders
    $policyContent = $policyContent -replace '\{\{contentUri\}\}', $sasToken
    $policyContent = $policyContent -replace '\{\{contentHash\}\}', $hash

    $tempPolicy = Join-Path $env:TEMP "$configName-policy.json"
    $policyContent | Set-Content $tempPolicy -Encoding UTF8

    $policyDef = New-AzPolicyDefinition `
        -Name $policyName `
        -DisplayName $displayName `
        -Policy $tempPolicy `
        -Mode 'Indexed'

    Remove-Item $tempPolicy -ErrorAction SilentlyContinue
} else {
    # Build a minimal AINE policy inline
    Write-Host "   No policy.json found — building minimal Audit policy inline" -ForegroundColor Yellow

    $effect = if ($Mode -eq 'AuditAndSet') { 'deployIfNotExists' } else { 'auditIfNotExists' }
    $configType = if ($Mode -eq 'AuditAndSet') { 'ApplyAndAutoCorrect' } else { 'Audit' }

    $policyRule = @{
        'if' = @{
            'anyOf' = @(
                @{ 'allOf' = @(
                    @{ 'field' = 'type'; 'equals' = 'Microsoft.Compute/virtualMachines' }
                )}
                @{ 'allOf' = @(
                    @{ 'field' = 'type'; 'equals' = 'Microsoft.HybridCompute/machines' }
                )}
            )
        }
        'then' = @{
            'effect' = $effect
            'details' = @{
                'type' = 'Microsoft.GuestConfiguration/guestConfigurationAssignments'
                'name' = $configName
                'existenceCondition' = @{
                    'allOf' = @(
                        @{ 'field' = 'Microsoft.GuestConfiguration/guestConfigurationAssignments/complianceStatus'; 'equals' = 'Compliant' }
                        @{ 'field' = 'Microsoft.GuestConfiguration/guestConfigurationAssignments/parameterHash'; 'equals' = '' }
                    )
                }
            }
        }
    }

    $policyObj = @{
        'properties' = @{
            'displayName' = $displayName
            'description' = "Machine Configuration policy for $configName (generated by MC Builder)"
            'policyType' = 'Custom'
            'mode' = 'Indexed'
            'policyRule' = $policyRule
            'metadata' = @{
                'category' = 'Guest Configuration'
                'guestConfiguration' = @{
                    'name' = $configName
                    'version' = '1.0.0'
                    'contentType' = 'Custom'
                    'contentUri' = $sasToken
                    'contentHash' = $hash
                    'configurationParameter' = @{}
                }
            }
        }
    }

    $tempPolicy = Join-Path $env:TEMP "$configName-policy.json"
    $policyObj | ConvertTo-Json -Depth 20 | Set-Content $tempPolicy -Encoding UTF8

    $policyDef = New-AzPolicyDefinition `
        -Name $policyName `
        -DisplayName $displayName `
        -Policy $tempPolicy `
        -Mode 'Indexed'

    Remove-Item $tempPolicy -ErrorAction SilentlyContinue
}

Write-Host "   ✅ Policy created: $($policyDef.Name)" -ForegroundColor Green
Write-Host "   ID: $($policyDef.PolicyDefinitionId)" -ForegroundColor Gray
Write-Host ''

# ─── Assign Policy ───────────────────────────────────────────────────────────

Write-Host '🎯 Assigning policy...' -ForegroundColor Cyan

$assignmentName = "assign-$configName"
if ($assignmentName.Length -gt 64) { $assignmentName = $assignmentName.Substring(0, 64) }

$assignParams = @{
    Name             = $assignmentName
    DisplayName      = "Assign: $displayName"
    PolicyDefinition = $policyDef
}

switch ($Scope) {
    'Subscription' {
        $assignParams.Scope = "/subscriptions/$subId"
        Write-Host "   Scope: Subscription ($($context.Subscription.Name))" -ForegroundColor Gray
    }
    'ResourceGroup' {
        $assignParams.Scope = "/subscriptions/$subId/resourceGroups/$ResourceGroupName"
        Write-Host "   Scope: Resource Group ($ResourceGroupName)" -ForegroundColor Gray
    }
    'VM' {
        # Try Azure VM first, then Arc
        $vm = Get-AzVM -ResourceGroupName $ResourceGroupName -Name $VMName -ErrorAction SilentlyContinue
        if ($vm) {
            $assignParams.Scope = $vm.Id
            Write-Host "   Scope: VM $VMName (Azure VM)" -ForegroundColor Gray
        } else {
            $arc = Get-AzConnectedMachine -ResourceGroupName $ResourceGroupName -Name $VMName -ErrorAction SilentlyContinue
            if ($arc) {
                $assignParams.Scope = $arc.Id
                Write-Host "   Scope: VM $VMName (Arc-enabled)" -ForegroundColor Gray
            } else {
                Write-Error "VM '$VMName' not found in resource group '$ResourceGroupName' (checked Azure VMs and Arc machines)"
                exit 1
            }
        }
    }
}

# For DINE policies, create a managed identity for remediation
if ($Mode -eq 'AuditAndSet') {
    $assignParams.Location = $Location
    $assignParams.IdentityType = 'SystemAssigned'
    Write-Host "   ℹ️  AuditAndSet mode — managed identity will be created for remediation" -ForegroundColor Gray
}

$assignment = New-AzPolicyAssignment @assignParams

Write-Host "   ✅ Policy assigned: $($assignment.Name)" -ForegroundColor Green
Write-Host ''

# For DINE, grant the managed identity Contributor on the scope
if ($Mode -eq 'AuditAndSet' -and $assignment.Identity.PrincipalId) {
    Write-Host '🔐 Granting remediation permissions...' -ForegroundColor Cyan
    $retries = 0
    while ($retries -lt 5) {
        try {
            New-AzRoleAssignment `
                -ObjectId $assignment.Identity.PrincipalId `
                -RoleDefinitionName 'Contributor' `
                -Scope $assignParams.Scope | Out-Null
            Write-Host "   ✅ Contributor role assigned to managed identity" -ForegroundColor Green
            break
        } catch {
            $retries++
            if ($retries -ge 5) { 
                Write-Host "   ⚠️  Could not assign role — you may need to do this manually" -ForegroundColor Yellow
            } else {
                Start-Sleep -Seconds 5
            }
        }
    }
    Write-Host ''
}

# ─── Summary ─────────────────────────────────────────────────────────────────

Write-Host "╔══════════════════════════════════════════════════════════════╗" -ForegroundColor Green
Write-Host "║  ✅ Deployment Complete                                      ║" -ForegroundColor Green
Write-Host "╚══════════════════════════════════════════════════════════════╝" -ForegroundColor Green
Write-Host ''
Write-Host "  Package:           $configName" -ForegroundColor White
Write-Host "  Storage:           $StorageAccountName/$ContainerName/$blobName" -ForegroundColor White
Write-Host "  Policy Definition: $($policyDef.PolicyDefinitionId)" -ForegroundColor White
Write-Host "  Policy Assignment: $($assignment.Name)" -ForegroundColor White
Write-Host "  Scope:             $($assignParams.Scope)" -ForegroundColor White
Write-Host ''
Write-Host '  ⏱  The GC agent evaluates every 15 minutes. Check compliance:' -ForegroundColor Gray
Write-Host "     Get-AzPolicyState -PolicyAssignmentName '$assignmentName'" -ForegroundColor Gray
Write-Host ''
Write-Host '  ⚠️  VM Prerequisites — ensure this built-in initiative is assigned:' -ForegroundColor Yellow
Write-Host '     "Deploy prerequisites to enable Guest Configuration policies on VMs"' -ForegroundColor Yellow
Write-Host '     Initiative ID: 12794019-7a00-42cf-95c2-882eed337cc8' -ForegroundColor Yellow
Write-Host '     Note: Arc-enabled servers already include the GC agent.' -ForegroundColor Gray
Write-Host ''
