import { ResourceSchema } from '../../types';

export const auditPolicySubcategorySchema: ResourceSchema = {
  resourceName: 'AuditPolicySubcategory',
  moduleName: 'AuditPolicyDsc',
  moduleVersion: '1.4.0.0',
  mofClassName: 'MSFT_AuditPolicySubcategory',
  dscV3TypeName: 'AuditPolicyDsc/AuditPolicySubcategory',
  platform: 'Windows',
  description: 'Configure advanced audit policy subcategory flags (e.g., logon events, object access)',
  docUrl: 'https://github.com/dsccommunity/AuditPolicyDsc',
  category: 'Audit Policy',
  properties: [
    {
      name: 'Name', description: 'Audit policy subcategory name', type: 'string', required: true, isKey: true, placeholder: 'Logon',
      enumValues: [
        'Security System Extension', 'System Integrity', 'IPsec Driver',
        'Other System Events', 'Security State Change',
        'Logon', 'Logoff', 'Account Lockout',
        'IPsec Main Mode', 'IPsec Quick Mode', 'IPsec Extended Mode',
        'Special Logon', 'Other Logon/Logoff Events', 'Network Policy Server',
        'User / Device Claims', 'Group Membership',
        'File System', 'Registry', 'Kernel Object', 'SAM',
        'Certification Services', 'Application Generated', 'Handle Manipulation',
        'File Share', 'Filtering Platform Packet Drop', 'Filtering Platform Connection',
        'Other Object Access Events', 'Detailed File Share',
        'Removable Storage', 'Central Policy Staging',
        'Sensitive Privilege Use', 'Non Sensitive Privilege Use', 'Other Privilege Use Events',
        'Process Creation', 'Process Termination', 'DPAPI Activity',
        'RPC Events', 'Plug and Play Events', 'Token Right Adjusted Events',
        'Audit Policy Change', 'Authentication Policy Change',
        'Authorization Policy Change', 'MPSSVC Rule-Level Policy Change',
        'Filtering Platform Policy Change', 'Other Policy Change Events',
        'User Account Management', 'Computer Account Management',
        'Security Group Management', 'Distribution Group Management',
        'Application Group Management', 'Other Account Management Events',
        'Directory Service Access', 'Directory Service Changes',
        'Directory Service Replication', 'Detailed Directory Service Replication',
        'Credential Validation', 'Kerberos Service Ticket Operations',
        'Other Account Logon Events', 'Kerberos Authentication Service',
      ],
    },
    { name: 'AuditFlag', description: 'Audit flag to apply', type: 'string', required: true, isKey: true, enumValues: ['Success', 'Failure'] },
    { name: 'Ensure', description: 'Whether the audit flag should be present or absent', type: 'string', required: false, isKey: false, enumValues: ['Present', 'Absent'], defaultValue: 'Present' },
  ],
};
