import { ResourceSchema } from '../../types';

export const firewallSchema: ResourceSchema = {
  resourceName: 'Firewall',
  moduleName: 'NetworkingDsc',
  moduleVersion: '9.0.0',
  mofClassName: 'DSC_Firewall',
  dscV3TypeName: 'NetworkingDsc/Firewall',
  platform: 'Windows',
  description: 'Manage Windows Firewall rules (allow/block, ports, protocols, programs)',
  docUrl: 'https://github.com/dsccommunity/NetworkingDsc/wiki/Firewall',
  category: 'Networking',
  properties: [
    { name: 'Name', description: 'Firewall rule name', type: 'string', required: true, isKey: true, placeholder: 'AllowHTTPS' },
    { name: 'DisplayName', description: 'User-facing rule display name', type: 'string', required: false, isKey: false },
    { name: 'Group', description: 'Firewall group name', type: 'string', required: false, isKey: false },
    { name: 'Ensure', description: 'Whether the rule should exist', type: 'string', required: false, isKey: false, enumValues: ['Present', 'Absent'], defaultValue: 'Present' },
    { name: 'Enabled', description: 'Enable or disable the rule', type: 'string', required: false, isKey: false, enumValues: ['True', 'False'], defaultValue: 'True' },
    { name: 'Action', description: 'Allow or block traffic', type: 'string', required: false, isKey: false, enumValues: ['NotConfigured', 'Allow', 'Block'], defaultValue: 'Allow' },
    { name: 'Direction', description: 'Traffic direction', type: 'string', required: false, isKey: false, enumValues: ['Inbound', 'Outbound'], defaultValue: 'Inbound' },
    { name: 'Profile', description: 'Firewall profiles the rule applies to', type: 'string[]', required: false, isKey: false, enumValues: ['Domain', 'Private', 'Public'] },
    { name: 'LocalPort', description: 'Local port numbers or ranges', type: 'string[]', required: false, isKey: false, placeholder: '443' },
    { name: 'RemotePort', description: 'Remote port numbers or ranges', type: 'string[]', required: false, isKey: false },
    { name: 'Protocol', description: 'Protocol name or number', type: 'string', required: false, isKey: false, placeholder: 'TCP' },
    { name: 'Program', description: 'Path to the program executable', type: 'string', required: false, isKey: false },
    { name: 'Service', description: 'Short name of the Windows service', type: 'string', required: false, isKey: false },
    { name: 'Description', description: 'Rule documentation', type: 'string', required: false, isKey: false },
    { name: 'LocalAddress', description: 'Local IP addresses', type: 'string[]', required: false, isKey: false },
    { name: 'RemoteAddress', description: 'Remote IP addresses', type: 'string[]', required: false, isKey: false },
    { name: 'Authentication', description: 'Authentication requirement', type: 'string', required: false, isKey: false, enumValues: ['NotRequired', 'Required', 'NoEncap'] },
    { name: 'Encryption', description: 'Encryption requirement', type: 'string', required: false, isKey: false, enumValues: ['NotRequired', 'Required', 'Dynamic'] },
    { name: 'InterfaceAlias', description: 'Network interface aliases', type: 'string[]', required: false, isKey: false },
    { name: 'InterfaceType', description: 'Interface type filter', type: 'string', required: false, isKey: false, enumValues: ['Any', 'Wired', 'Wireless', 'RemoteAccess'] },
  ],
};
