import { ResourceSchema } from '../../types';

export const scheduledTaskSchema: ResourceSchema = {
  resourceName: 'ScheduledTask',
  moduleName: 'ComputerManagementDsc',
  moduleVersion: '9.2.0',
  mofClassName: 'DSC_ScheduledTask',
  dscV3TypeName: 'ComputerManagementDsc/ScheduledTask',
  platform: 'Windows',
  description: 'Create or manage Windows scheduled tasks',
  docUrl: 'https://github.com/dsccommunity/ComputerManagementDsc/wiki/ScheduledTask',
  category: 'System',
  properties: [
    { name: 'TaskName', description: 'Name of the scheduled task', type: 'string', required: true, isKey: true, placeholder: 'DailyBackup' },
    { name: 'TaskPath', description: 'Task scheduler folder path', type: 'string', required: false, isKey: false, placeholder: '\\MyTasks\\' },
    { name: 'Ensure', description: 'Whether the task should exist', type: 'string', required: false, isKey: false, enumValues: ['Present', 'Absent'], defaultValue: 'Present' },
    { name: 'Enable', description: 'Enable or disable the task', type: 'boolean', required: false, isKey: false, defaultValue: true },
    { name: 'ActionExecutable', description: 'Path to the executable to run', type: 'string', required: false, isKey: false, placeholder: 'C:\\Scripts\\backup.ps1' },
    { name: 'ActionArguments', description: 'Arguments passed to the executable', type: 'string', required: false, isKey: false },
    { name: 'ActionWorkingPath', description: 'Working directory for the action', type: 'string', required: false, isKey: false },
    { name: 'ScheduleType', description: 'Type of schedule trigger', type: 'string', required: false, isKey: false, enumValues: ['Once', 'Daily', 'Weekly', 'AtStartup', 'AtLogOn', 'OnEvent'] },
    { name: 'RepeatInterval', description: 'How often to repeat (e.g., 00:15:00 for 15 min)', type: 'string', required: false, isKey: false, validationPattern: '^\\d{1,2}:\\d{2}:\\d{2}$', validationMessage: 'RepeatInterval must be in HH:MM:SS format (e.g. 00:15:00)' },
    { name: 'RepetitionDuration', description: 'How long to keep repeating (e.g., 08:00:00)', type: 'string', required: false, isKey: false, validationPattern: '^(Indefinitely|\\d{1,2}:\\d{2}:\\d{2})$', validationMessage: 'RepetitionDuration must be HH:MM:SS or "Indefinitely"' },
    { name: 'StartTime', description: 'Start date/time for the trigger', type: 'string', required: false, isKey: false, placeholder: '2024-01-01T08:00:00' },
    { name: 'DaysInterval', description: 'For Daily schedule: run every N days', type: 'integer', required: false, isKey: false },
    { name: 'WeeksInterval', description: 'For Weekly schedule: run every N weeks', type: 'integer', required: false, isKey: false },
    { name: 'DaysOfWeek', description: 'Days of the week for Weekly schedule', type: 'string[]', required: false, isKey: false, enumValues: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'] },
    { name: 'ExecuteAsCredential', description: 'User account to run the task as', type: 'string', required: false, isKey: false, placeholder: 'SYSTEM' },
    { name: 'RunLevel', description: 'Run with limited or highest privileges', type: 'string', required: false, isKey: false, enumValues: ['Limited', 'Highest'] },
    { name: 'Description', description: 'Task description', type: 'string', required: false, isKey: false },
    { name: 'Priority', description: 'Task priority (0 = highest, 10 = lowest)', type: 'integer', required: false, isKey: false, defaultValue: 7 },
    { name: 'Hidden', description: 'Hide task in Task Scheduler UI', type: 'boolean', required: false, isKey: false, defaultValue: false },
    { name: 'RunOnlyIfNetworkAvailable', description: 'Only run when network is available', type: 'boolean', required: false, isKey: false, defaultValue: false },
    { name: 'DisallowStartIfOnBatteries', description: 'Do not start if on battery power', type: 'boolean', required: false, isKey: false, defaultValue: false },
  ],
};
