import { ResourceSchema } from '../../types';

export const userRightsAssignmentSchema: ResourceSchema = {
  resourceName: 'UserRightsAssignment',
  moduleName: 'SecurityPolicyDsc',
  moduleVersion: '2.10.0.0',
  mofClassName: 'MSFT_UserRightsAssignment',
  dscV3TypeName: 'SecurityPolicyDsc/UserRightsAssignment',
  platform: 'Windows',
  description: 'Configure user rights assignments (e.g., allow/deny logon, backup, shutdown)',
  docUrl: 'https://github.com/dsccommunity/SecurityPolicyDsc',
  category: 'Security Policy',
  properties: [
    {
      name: 'Policy', description: 'The user rights assignment policy name', type: 'string', required: true, isKey: true,
      enumValues: [
        'Create_a_token_object', 'Access_this_computer_from_the_network',
        'Change_the_system_time', 'Deny_log_on_as_a_service',
        'Deny_log_on_locally', 'Deny_log_on_through_Remote_Desktop_Services',
        'Deny_access_to_this_computer_from_the_network',
        'Allow_log_on_locally', 'Allow_log_on_through_Remote_Desktop_Services',
        'Back_up_files_and_directories', 'Restore_files_and_directories',
        'Shut_down_the_system', 'Force_shutdown_from_a_remote_system',
        'Manage_auditing_and_security_log', 'Take_ownership_of_files_or_other_objects',
        'Debug_programs', 'Generate_security_audits',
        'Load_and_unload_device_drivers', 'Act_as_part_of_the_operating_system',
        'Impersonate_a_client_after_authentication', 'Log_on_as_a_batch_job',
        'Log_on_as_a_service', 'Deny_log_on_as_a_batch_job',
        'Replace_a_process_level_token', 'Increase_scheduling_priority',
        'Lock_pages_in_memory', 'Bypass_traverse_checking',
        'Remove_computer_from_docking_station', 'Profile_single_process',
        'Profile_system_performance', 'Perform_volume_maintenance_tasks',
        'Modify_firmware_environment_values', 'Add_workstations_to_domain',
        'Adjust_memory_quotas_for_a_process',
        'Enable_computer_and_user_accounts_to_be_trusted_for_delegation',
        'Synchronize_directory_service_data', 'Modify_an_object_label',
        'Increase_a_process_working_set', 'Access_Credential_Manager_as_a_trusted_caller',
        'Create_global_objects', 'Create_permanent_shared_objects', 'Create_symbolic_links',
      ],
    },
    { name: 'Identity', description: 'Identities to assign the right to (e.g., Administrators, BUILTIN\\Users)', type: 'string[]', required: true, isKey: false, placeholder: 'Administrators' },
    { name: 'Force', description: 'Replace all existing identities (true) or ensure listed ones are present (false)', type: 'boolean', required: false, isKey: false, defaultValue: false },
  ],
};
