import { ConfigurationState } from '../types';

/** Sanitise a DSC identifier (config name). Must match [a-zA-Z_][a-zA-Z0-9_]* */
function sanitiseIdentifier(value: string): string {
  const cleaned = value.replace(/[^a-zA-Z0-9_]/g, '');
  return /^[a-zA-Z_]/.test(cleaned) ? cleaned : `_${cleaned}`;
}

// Helper: produce a PS Write-Host line that shows a literal dollar sign.
// Inside a double-quoted PS string the backtick escapes the dollar: `$var
// But backtick+dollar inside a JS template literal would start an expression,
// so we build the string via concatenation instead.
const DLR = '`$'; // PS escaped dollar

function remediationBlock(safeName: string): string {
  return `
# ─── AuditAndSet: Remediation Instructions ───────────────────────────────────

Write-Host '╔══════════════════════════════════════════════════════════════╗' -ForegroundColor Yellow
Write-Host '║  IMPORTANT: AuditAndSet Mode — Remediation Task Required     ║' -ForegroundColor Yellow
Write-Host '╚══════════════════════════════════════════════════════════════╝' -ForegroundColor Yellow
Write-Host ''
Write-Host '  This config uses AuditAndSet (remediation) mode.' -ForegroundColor Yellow
Write-Host '  Azure DINE policies have a two-stage deployment:' -ForegroundColor Yellow
Write-Host ''
Write-Host '  Stage 1: Policy assignment evaluates compliance (Audit only)' -ForegroundColor Gray
Write-Host '  Stage 2: Remediation task triggers the actual ApplyAndAutoCorrect' -ForegroundColor Gray
Write-Host ''
Write-Host '  After assigning the policy, you MUST create a remediation task:' -ForegroundColor Yellow
Write-Host ''
Write-Host '  Option A — Azure Portal:' -ForegroundColor Cyan
Write-Host '    1. Go to Policy > Assignments > select this assignment' -ForegroundColor Gray
Write-Host '    2. Click "Create Remediation Task"' -ForegroundColor Gray
Write-Host '    3. Wait for the task to complete (~15 min)' -ForegroundColor Gray
Write-Host ''
Write-Host '  Option B — PowerShell:' -ForegroundColor Cyan
Write-Host "    ${DLR}assignment = Get-AzPolicyAssignment | Where-Object { ${DLR}_.PolicyDefinitionId -like '*$policyName*' }" -ForegroundColor Gray
Write-Host "    Start-AzPolicyRemediation -Name '$configName-remediation' -PolicyAssignmentId ${DLR}assignment.PolicyAssignmentId" -ForegroundColor Gray
Write-Host ''
`;
}

/**
 * Generate a deploy.ps1 script for the config bundle.
 * This script:
 *   1. Authenticates to Azure (interactive Connect-AzAccount)
 *   2. Uploads the sibling ZIP to blob storage
 *   3. Creates the policy definition using the sibling policy.json
 *   4. For AuditAndSet: explains the remediation task requirement
 *   5. Prints next steps: assign from Azure Portal
 */
export function generateDeployScript(config: ConfigurationState): string {
  const safeName = sanitiseIdentifier(config.configName);
  const isRemediation = config.mode === 'AuditAndSet';

  const lines: string[] = [];

  lines.push(`# deploy.ps1 — Upload package and create Azure Policy definition
# Generated by Azure Machine Configuration Builder
#
# Usage (run from the folder containing this file):
#   pwsh ./deploy.ps1
#   pwsh ./deploy.ps1 -SkipLogin              # if you are already authenticated
#   pwsh ./deploy.ps1 -StorageAccountName mystorage -ResourceGroupName myRG
#
# What this does:
#   1. Authenticates to Azure interactively
#   2. Uploads the deployable ZIP to Azure Blob Storage
#   3. Creates an Azure Policy definition using policy.json`);

  if (isRemediation) {
    lines.push(`#   4. Prints remediation instructions (AuditAndSet mode)`);
  }

  lines.push(`#
# After completion, assign the policy from the Azure Portal or with:
#   $def = Get-AzPolicyDefinition -Name 'MC-${safeName}'
#   New-AzPolicyAssignment -Name 'MyAssignment' -PolicyDefinition $def -Scope '/subscriptions/<sub-id>'

#Requires -Version 7.0
#Requires -Modules Az.Accounts, Az.Storage, Az.Resources

[CmdletBinding()]
param(
    [string]$StorageAccountName,
    [string]$ResourceGroupName,
    [string]$StorageResourceGroup,
    [string]$ContainerName = 'guestconfiguration',
    [string]$Location = 'uksouth',
    [string]$SubscriptionId,
    [switch]$SkipLogin
)

$ErrorActionPreference = 'Stop'

# ─── Ensure $env:TEMP is set (Linux doesn't set it by default) ───────────────
if (-not $env:TEMP) { $env:TEMP = [System.IO.Path]::GetTempPath() }

$configName = '${safeName}'
$scriptDir  = $PSScriptRoot

# ─── Locate the deployable ZIP ───────────────────────────────────────────────
# package.ps1 places it in output\\<configName>.zip
$zipPath = Join-Path $scriptDir "output\\$configName.zip"
if (-not (Test-Path $zipPath)) {
    # Fallback: look for any .zip in output/ or alongside this script
    $zipPath = Get-ChildItem -Path (Join-Path $scriptDir 'output') -Filter '*.zip' -ErrorAction SilentlyContinue |
               Select-Object -First 1 -ExpandProperty FullName
}
if (-not $zipPath -or -not (Test-Path $zipPath)) {
    Write-Error "No deployable ZIP found. Run package.ps1 first to create output\\$configName.zip"
    exit 1
}

$policyJsonPath = Join-Path $scriptDir 'policy.json'
if (-not (Test-Path $policyJsonPath)) {
    Write-Error "policy.json not found at: $policyJsonPath"
    exit 1
}

$hash = (Get-FileHash -Path $zipPath -Algorithm SHA256).Hash

Write-Host ''
Write-Host "╔══════════════════════════════════════════════════════════════╗" -ForegroundColor Cyan
Write-Host "║  Azure Machine Configuration — Deploy                        ║" -ForegroundColor Cyan
Write-Host "╚══════════════════════════════════════════════════════════════╝" -ForegroundColor Cyan
Write-Host "  Config:  $configName" -ForegroundColor Gray
Write-Host "  Package: $zipPath" -ForegroundColor Gray
Write-Host "  Hash:    $($hash.Substring(0,16))..." -ForegroundColor Gray`);

  // Mode line — different color for remediation
  if (isRemediation) {
    lines.push(`Write-Host "  Mode:    AuditAndSet (Remediation)" -ForegroundColor Yellow`);
  } else {
    lines.push(`Write-Host "  Mode:    Audit (Monitor Only)" -ForegroundColor Gray`);
  }

  lines.push(`Write-Host ''

# ─── Azure Login ──────────────────────────────────────────────────────────────

if (-not $SkipLogin) {
    $context = Get-AzContext -ErrorAction SilentlyContinue
    if (-not $context) {
        Write-Host '[AUTH] Connecting to Azure...' -ForegroundColor Cyan
        Connect-AzAccount
        $context = Get-AzContext
    } else {
        Write-Host "[AUTH] Using existing context: $($context.Account.Id)" -ForegroundColor Gray
    }
}

if ($SubscriptionId) {
    Set-AzContext -SubscriptionId $SubscriptionId | Out-Null
}

$context = Get-AzContext
$subId   = $context.Subscription.Id
Write-Host "   Subscription: $($context.Subscription.Name) ($subId)" -ForegroundColor Gray
Write-Host ''

# ─── Storage Account ─────────────────────────────────────────────────────────

$storageRg = if ($StorageResourceGroup) { $StorageResourceGroup } elseif ($ResourceGroupName) { $ResourceGroupName } else { "MC-Packages-$($subId.Substring(0,8))" }

if (-not $StorageAccountName) {
    $StorageAccountName = "mcpkgs$($subId.Substring(0,8).ToLower() -replace '[^a-z0-9]','')"
    if ($StorageAccountName.Length -gt 24) { $StorageAccountName = $StorageAccountName.Substring(0, 24) }
}

Write-Host '[STORAGE] Setting up storage...' -ForegroundColor Cyan

$storage = Get-AzStorageAccount | Where-Object { $_.StorageAccountName -eq $StorageAccountName } | Select-Object -First 1
if (-not $storage) {
    $rg = Get-AzResourceGroup -Name $storageRg -ErrorAction SilentlyContinue
    if (-not $rg) {
        Write-Host "   Creating resource group: $storageRg" -ForegroundColor Gray
        New-AzResourceGroup -Name $storageRg -Location $Location | Out-Null
    }
    Write-Host "   Creating storage account: $StorageAccountName" -ForegroundColor Gray
    $storage = New-AzStorageAccount \`
        -ResourceGroupName $storageRg \`
        -Name $StorageAccountName \`
        -Location $Location \`
        -SkuName Standard_LRS \`
        -Kind StorageV2 \`
        -AllowBlobPublicAccess $false
} else {
    Write-Host "   Using existing storage: $StorageAccountName" -ForegroundColor Gray
}

$storageCtx = $storage.Context

$container = Get-AzStorageContainer -Name $ContainerName -Context $storageCtx -ErrorAction SilentlyContinue
if (-not $container) {
    Write-Host "   Creating container: $ContainerName" -ForegroundColor Gray
    New-AzStorageContainer -Name $ContainerName -Context $storageCtx -Permission Off | Out-Null
}

# ─── Upload Package ──────────────────────────────────────────────────────────

$blobName = "$configName-$($hash.Substring(0,8).ToLower()).zip"
Write-Host "   Uploading $blobName..." -ForegroundColor Gray

Set-AzStorageBlobContent \`
    -File $zipPath \`
    -Container $ContainerName \`
    -Blob $blobName \`
    -Context $storageCtx \`
    -Force | Out-Null

$sasExpiry = (Get-Date).AddYears(3)
$sasToken = New-AzStorageBlobSASToken \`
    -Container $ContainerName \`
    -Blob $blobName \`
    -Permission r \`
    -ExpiryTime $sasExpiry \`
    -Context $storageCtx \`
    -FullUri

Write-Host "   [OK] Uploaded (SAS expires $($sasExpiry.ToString('yyyy-MM-dd')))" -ForegroundColor Green
Write-Host ''

# ─── Create Policy Definition ────────────────────────────────────────────────

Write-Host '[POLICY] Creating policy definition...' -ForegroundColor Cyan

$policyName   = "MC-$configName"
$displayName  = "Machine Configuration: $configName"

# Remove existing definition if present (clean redeploy)
try {
    $existingDef = Get-AzPolicyDefinition -Name $policyName -ErrorAction SilentlyContinue 2>$null
    if ($existingDef) {
        Write-Host "   [CLEANUP] Removing existing definition: $policyName" -ForegroundColor Yellow
        Remove-AzPolicyDefinition -Name $policyName -Force -ErrorAction SilentlyContinue
        Start-Sleep -Seconds 5
    }
} catch {}

$policyContent = Get-Content $policyJsonPath -Raw
$policyContent = $policyContent -replace '\\{\\{contentUri\\}\\}',  $sasToken
$policyContent = $policyContent -replace '\\{\\{contentHash\\}\\}', $hash

$tempPolicy = Join-Path $env:TEMP "$configName-policy.json"
$policyContent | Set-Content $tempPolicy -Encoding UTF8

$policyDef = New-AzPolicyDefinition \`
    -Name $policyName \`
    -DisplayName $displayName \`
    -Policy $tempPolicy \`
    -Mode 'Indexed'

Remove-Item $tempPolicy -ErrorAction SilentlyContinue

Write-Host "   [OK] Policy definition created: $($policyDef.Name)" -ForegroundColor Green
Write-Host "   ID: $($policyDef.PolicyDefinitionId)" -ForegroundColor Gray
Write-Host ''`);

  // AuditAndSet remediation instructions
  if (isRemediation) {
    lines.push(`
# ─── AuditAndSet: Remediation Instructions ───────────────────────────────────

Write-Host '╔══════════════════════════════════════════════════════════════╗' -ForegroundColor Yellow
Write-Host '║  IMPORTANT: AuditAndSet Mode — Remediation Task Required     ║' -ForegroundColor Yellow
Write-Host '╚══════════════════════════════════════════════════════════════╝' -ForegroundColor Yellow
Write-Host ''
Write-Host '  This config uses AuditAndSet (remediation) mode.' -ForegroundColor Yellow
Write-Host '  Azure DINE policies have a two-stage deployment:' -ForegroundColor Yellow
Write-Host ''
Write-Host '  Stage 1: Policy assignment evaluates compliance (Audit only)' -ForegroundColor Gray
Write-Host '  Stage 2: Remediation task triggers the actual ApplyAndAutoCorrect' -ForegroundColor Gray
Write-Host ''
Write-Host '  After assigning the policy, you MUST create a remediation task:' -ForegroundColor Yellow
Write-Host ''
Write-Host '  Option A — Azure Portal:' -ForegroundColor Cyan
Write-Host '    1. Go to Policy > Assignments > select this assignment' -ForegroundColor Gray
Write-Host '    2. Click "Create Remediation Task"' -ForegroundColor Gray
Write-Host '    3. Wait for the task to complete (~15 min)' -ForegroundColor Gray
Write-Host ''
Write-Host '  Option B — PowerShell:' -ForegroundColor Cyan`);

    // Lines with PS $variables — use DLR constant to avoid JS template literal issues
    lines.push(
      "Write-Host \"    " + DLR + "assignment = Get-AzPolicyAssignment | Where-Object { " + DLR + "_.PolicyDefinitionId -like '*$policyName*' }\" -ForegroundColor Gray",
      "Write-Host \"    Start-AzPolicyRemediation -Name '$configName-remediation' -PolicyAssignmentId " + DLR + "assignment.PolicyAssignmentId\" -ForegroundColor Gray",
      "Write-Host ''",
    );
  }

  // Summary
  lines.push(`
# ─── Summary ─────────────────────────────────────────────────────────────────

Write-Host "╔══════════════════════════════════════════════════════════════╗" -ForegroundColor Green
Write-Host "║  Done                                                        ║" -ForegroundColor Green
Write-Host "╚══════════════════════════════════════════════════════════════╝" -ForegroundColor Green
Write-Host ''
Write-Host "  Config:            $configName" -ForegroundColor White`);

  if (isRemediation) {
    lines.push(`Write-Host "  Mode:              AuditAndSet (Remediation)" -ForegroundColor White`);
  } else {
    lines.push(`Write-Host "  Mode:              Audit (Monitor Only)" -ForegroundColor White`);
  }

  lines.push(`Write-Host "  Hash:              $($hash.Substring(0,16))..." -ForegroundColor White
Write-Host "  Storage:           $StorageAccountName/$ContainerName/$blobName" -ForegroundColor White
Write-Host "  Policy Definition: $($policyDef.PolicyDefinitionId)" -ForegroundColor White
Write-Host ''
Write-Host '  Policy definition created. Assign it from Azure Portal.' -ForegroundColor Green`);

  if (isRemediation) {
    lines.push(`Write-Host '  Remember: Create a remediation task after assignment to enable remediation!' -ForegroundColor Yellow`);
  }

  lines.push(`Write-Host ''
Write-Host '  Or assign via PowerShell:'`);

  // More PS $variable lines
  lines.push(
    "Write-Host \"     " + DLR + "def = Get-AzPolicyDefinition -Name '$policyName'\" -ForegroundColor Gray",
    "Write-Host \"     New-AzPolicyAssignment -Name 'MyAssignment' -PolicyDefinition " + DLR + "def -Scope '/subscriptions/$subId'\" -ForegroundColor Gray",
  );

  if (isRemediation) {
    lines.push(
      "Write-Host \"     Start-AzPolicyRemediation -Name '" + safeName + "-remediation' -PolicyAssignmentId " + DLR + "assignment.PolicyAssignmentId\" -ForegroundColor Gray",
    );
  }

  lines.push(`Write-Host ''
`);

  return lines.join('\n');
}
