import { ConfigurationState } from '../types';
import { assertValidIdentifiers } from '../utils/configuration';

// Helper: produce a PS Write-Host line that shows a literal dollar sign.
// Inside a double-quoted PS string the backtick escapes the dollar: `$var
// But backtick+dollar inside a JS template literal would start an expression,
// so we build the string via concatenation instead.
const DLR = '`$'; // PS escaped dollar

/**
 * Generate a deploy.ps1 script for the config bundle.
 * This script:
 *   1. Authenticates to Azure (interactive Connect-AzAccount)
 *   2. Uploads the sibling ZIP to blob storage
 *   3. Creates the policy definition using the sibling policy.json
 *   4. For AuditAndSet: explains the remediation task requirement
 *   5. Prints next steps: assign from Azure Portal
 */
export function generateDeployScript(config: ConfigurationState): string {
  assertValidIdentifiers(config);
  const safeName = config.configName;
  const isRemediation = config.mode === 'AuditAndSet';

  const lines: string[] = [];

  lines.push(`# deploy.ps1 — Upload package and create Azure Policy definition
# Generated by Azure Machine Configuration Builder
#
# Usage (run from the folder containing this file):
#   pwsh ./deploy.ps1
#   pwsh ./deploy.ps1 -SkipLogin              # if you are already authenticated
#   pwsh ./deploy.ps1 -StorageAccountName mystorage -ResourceGroupName myRG
#
# What this does:
#   1. Authenticates to Azure interactively
#   2. Uploads the deployable ZIP to Azure Blob Storage
#   3. Creates an Azure Policy definition using policy.json`);

  if (isRemediation) {
    lines.push(`#   4. Prints remediation instructions (AuditAndSet mode)`);
  }

  lines.push(`#
# After completion, assign the policy from the Azure Portal or with:
#   $def = Get-AzPolicyDefinition -Name 'MC-${safeName}'
#   New-AzPolicyAssignment -Name 'MyAssignment' -PolicyDefinition $def -Scope '/subscriptions/<sub-id>'
# For AuditAndSet, follow the README identity/RBAC and remediation steps instead.

#Requires -Version 7.0
# Requires Az.Accounts, Az.Resources, Az.Storage

[CmdletBinding()]
param(
    [string]$StorageAccountName,
    [string]$ResourceGroupName,
    [string]$StorageResourceGroup,
    [string]$ContainerName = 'guestconfiguration',
    [string]$Location = 'uksouth',
    [string]$SubscriptionId,
    [ValidateSet('UserDelegation', 'SharedKey')]
    [string]$StorageAuthMode = 'UserDelegation',
    [ValidateRange(1, 1095)]
    [int]$SasExpiryDays = 6,
    [switch]$SkipLogin
)

$ErrorActionPreference = 'Stop'

function Fail($msg) {
    Write-Error $msg
    exit 1
}

if ($StorageAuthMode -eq 'UserDelegation' -and $SasExpiryDays -gt 6) {
    Fail 'User delegation SAS lifetime must be 1-6 days (the delegation key limit is 7 days). Use explicit SharedKey mode only if your storage policy permits it.'
}

# ─── Az module checks ───────────────────────────────────────────────────────
$requiredModules = @('Az.Accounts', 'Az.Resources', 'Az.Storage')
foreach ($m in $requiredModules) {
    if (-not (Get-Module -ListAvailable -Name $m)) {
        Fail "Required module '$m' is not installed. Run: Install-Module $($requiredModules -join ', ') -Scope CurrentUser"
    }
}

# ─── Ensure $env:TEMP is set (Linux doesn't set it by default) ───────────────
if (-not $env:TEMP) { $env:TEMP = [System.IO.Path]::GetTempPath() }

$configName = '${safeName}'
$scriptDir  = $PSScriptRoot

# ─── Locate the deployable ZIP ───────────────────────────────────────────────
# package.ps1 places it in output\\<configName>.zip
$zipPath = Join-Path $scriptDir "output\\$configName.zip"
if (-not $zipPath -or -not (Test-Path $zipPath)) {
    Write-Error "No deployable ZIP found. Run package.ps1 first to create output\\$configName.zip"
    exit 1
}

$policyJsonPath = Join-Path $scriptDir 'policy.json'
if (-not (Test-Path $policyJsonPath)) {
    Write-Error "policy.json not found at: $policyJsonPath"
    exit 1
}

$hash = (Get-FileHash -Path $zipPath -Algorithm SHA256).Hash

Write-Host ''
Write-Host "╔══════════════════════════════════════════════════════════════╗" -ForegroundColor Cyan
Write-Host "║  Azure Machine Configuration — Deploy                        ║" -ForegroundColor Cyan
Write-Host "╚══════════════════════════════════════════════════════════════╝" -ForegroundColor Cyan
Write-Host "  Config:  $configName" -ForegroundColor Gray
Write-Host "  Package: $zipPath" -ForegroundColor Gray
Write-Host "  Hash:    $($hash.Substring(0,16))..." -ForegroundColor Gray`);

  // Mode line — different color for remediation
  if (isRemediation) {
    lines.push(`Write-Host "  Mode:    AuditAndSet (Remediation)" -ForegroundColor Yellow`);
  } else {
    lines.push(`Write-Host "  Mode:    Audit (Monitor Only)" -ForegroundColor Gray`);
  }

  lines.push(`Write-Host ''

# ─── Azure Login ──────────────────────────────────────────────────────────────

if (-not $SkipLogin) {
    $context = Get-AzContext -ErrorAction SilentlyContinue
    if (-not $context) {
        Write-Host '[AUTH] Connecting to Azure...' -ForegroundColor Cyan
        try {
            Connect-AzAccount | Out-Null
        } catch {
            Fail "Azure login failed. Run Connect-AzAccount manually and retry. Details: $($_.Exception.Message)"
        }
        $context = Get-AzContext
    } else {
        Write-Host "[AUTH] Using existing context: $($context.Account.Id)" -ForegroundColor Gray
    }
} else {
    $context = Get-AzContext -ErrorAction SilentlyContinue
    if (-not $context) {
        Fail "-SkipLogin was specified but no Azure context was found. Run Connect-AzAccount or remove -SkipLogin."
    }
}

if ($SubscriptionId) {
    try {
        Set-AzContext -SubscriptionId $SubscriptionId | Out-Null
    } catch {
        Fail "Failed to set subscription '$SubscriptionId'. Check access or subscription ID."
    }
}

$context = Get-AzContext
$subId   = $context.Subscription.Id
Write-Host "   Subscription: $($context.Subscription.Name) ($subId)" -ForegroundColor Gray
Write-Host ''

# ─── Storage Account ─────────────────────────────────────────────────────────

$storageRg = if ($StorageResourceGroup) { $StorageResourceGroup } elseif ($ResourceGroupName) { $ResourceGroupName } else { "MC-Packages-$($subId.Substring(0,8))" }
$useExistingAccount = $StorageAccountName -and $StorageAuthMode -eq 'UserDelegation'

if (-not $StorageAccountName) {
    $StorageAccountName = "mcpkgs$($subId.Substring(0,8).ToLower() -replace '[^a-z0-9]','')"
    if ($StorageAccountName.Length -gt 24) { $StorageAccountName = $StorageAccountName.Substring(0, 24) }
}

Write-Host '[STORAGE] Setting up storage...' -ForegroundColor Cyan

$storage = $null
if ($useExistingAccount) {
    Write-Host "   Using existing storage with Microsoft Entra ID: $StorageAccountName" -ForegroundColor Gray
} elseif ($StorageResourceGroup -or $ResourceGroupName) {
    try {
        $storage = Get-AzStorageAccount -ResourceGroupName $storageRg -ErrorAction Stop |
            Where-Object { $_.StorageAccountName -eq $StorageAccountName }
    } catch {
        Fail "Failed to query storage account '$StorageAccountName' in RG '$storageRg'. Check permissions. Details: $($_.Exception.Message)"
    }
} else {
    try {
        $storageMatches = @(Get-AzStorageAccount -ErrorAction Stop | Where-Object { $_.StorageAccountName -eq $StorageAccountName })
    } catch {
        Fail "Failed to list storage accounts. Check permissions. Details: $($_.Exception.Message)"
    }
    if ($storageMatches.Count -gt 1) {
        Fail "Multiple storage accounts named '$StorageAccountName' found. Specify -ResourceGroupName or -StorageResourceGroup."
    }
    $storage = $storageMatches | Select-Object -First 1
}

if (-not $storage -and -not $useExistingAccount) {
    $rg = Get-AzResourceGroup -Name $storageRg -ErrorAction SilentlyContinue
    if (-not $rg) {
        Write-Host "   Creating resource group: $storageRg" -ForegroundColor Gray
        try {
            New-AzResourceGroup -Name $storageRg -Location $Location | Out-Null
        } catch {
            Fail "Failed to create resource group '$storageRg'. Check permissions. Details: $($_.Exception.Message)"
        }
    }
    Write-Host "   Creating storage account: $StorageAccountName" -ForegroundColor Gray
    try {
        $storage = New-AzStorageAccount \`
            -ResourceGroupName $storageRg \`
            -Name $StorageAccountName \`
            -Location $Location \`
            -SkuName Standard_LRS \`
            -Kind StorageV2 \`
            -AllowBlobPublicAccess $false
    } catch {
        Fail "Failed to create storage account '$StorageAccountName'. The name may already be taken or you may lack permissions. Details: $($_.Exception.Message)"
    }
} else {
    Write-Host "   Using existing storage: $StorageAccountName" -ForegroundColor Gray
}

if ($StorageAuthMode -eq 'UserDelegation') {
    $storageCtx = New-AzStorageContext -StorageAccountName $StorageAccountName -UseConnectedAccount -Environment $context.Environment.Name
} else {
    if ($storage.AllowSharedKeyAccess -eq $false) {
        Fail 'This storage account disables Shared Key access. Use -StorageAuthMode UserDelegation.'
    }
    Write-Warning 'SharedKey mode explicitly uses an account key. Prefer UserDelegation where possible.'
    $storageKey = (Get-AzStorageAccountKey -ResourceGroupName $storage.ResourceGroupName -Name $StorageAccountName -ErrorAction Stop)[0].Value
    $storageCtx = New-AzStorageContext -StorageAccountName $StorageAccountName -StorageAccountKey $storageKey -Environment $context.Environment.Name
}

try {
    $container = Get-AzStorageContainer -Context $storageCtx -ErrorAction Stop | Where-Object { $_.Name -eq $ContainerName }
} catch {
    Fail 'Cannot access blob storage. UserDelegation requires Storage Blob Data Contributor at storage-account scope (including delegation-key permission) and network access. No Shared Key fallback was attempted.'
}
if (-not $container) {
    Write-Host "   Creating container: $ContainerName" -ForegroundColor Gray
    try {
        New-AzStorageContainer -Name $ContainerName -Context $storageCtx -Permission Off | Out-Null
    } catch {
        Fail "Failed to create storage container '$ContainerName'. Check permissions. Details: $($_.Exception.Message)"
    }
}

# ─── Upload Package ──────────────────────────────────────────────────────────

$blobName = "$configName-$($hash.Substring(0,8).ToLower()).zip"
Write-Host "   Uploading $blobName..." -ForegroundColor Gray

try {
    Set-AzStorageBlobContent \`
        -File $zipPath \`
        -Container $ContainerName \`
        -Blob $blobName \`
        -Context $storageCtx \`
        -Force | Out-Null
} catch {
    Fail "Failed to upload package to storage. Check network and permissions. Details: $($_.Exception.Message)"
}

$sasStart = (Get-Date).ToUniversalTime().AddMinutes(-5)
$sasExpiry = (Get-Date).ToUniversalTime().AddDays($SasExpiryDays)
try {
    $sasToken = New-AzStorageBlobSASToken \`
        -Container $ContainerName \`
        -Blob $blobName \`
        -Permission r \`
        -Protocol HttpsOnly \`
        -StartTime $sasStart \`
        -ExpiryTime $sasExpiry \`
        -Context $storageCtx \`
        -FullUri
} catch {
    Fail "Failed to generate SAS URL. Check permissions. Details: $($_.Exception.Message)"
}

Write-Host "   [OK] Uploaded (SAS expires $($sasExpiry.ToString('yyyy-MM-dd')))" -ForegroundColor Green
Write-Warning "Renew the SAS and re-run this script before $($sasExpiry.ToString('yyyy-MM-dd HH:mm')) UTC. Expired URLs prevent package downloads."
Write-Host ''

# ─── Create Policy Definition ────────────────────────────────────────────────

Write-Host '[POLICY] Creating policy definition...' -ForegroundColor Cyan

$policyName   = "MC-$configName"
$displayName  = "Machine Configuration: $configName"

$policyContent = Get-Content $policyJsonPath -Raw
$policyContent = $policyContent.Replace('"{{contentUri}}"', (ConvertTo-Json -InputObject $sasToken -Compress))
$policyContent = $policyContent.Replace('"{{contentHash}}"', (ConvertTo-Json -InputObject $hash -Compress))
$null = $policyContent | ConvertFrom-Json

# New-AzPolicyDefinition is an upsert; never delete an assigned definition.
try {
    $policyDef = New-AzPolicyDefinition \`
        -Name $policyName \`
        -DisplayName $displayName \`
        -Policy $policyContent \`
        -SubscriptionId $subId \`
        -Mode 'Indexed'
} catch {
    Fail "Failed to create policy definition '$policyName'. Check permissions (Policy Contributor) and policy JSON. Details: $($_.Exception.Message)"
}

Write-Host "   [OK] Policy definition created: $($policyDef.Name)" -ForegroundColor Green
Write-Host "   ID: $($policyDef.Id)" -ForegroundColor Gray
Write-Host ''`);

  // AuditAndSet remediation instructions
  if (isRemediation) {
    lines.push(`
# ─── AuditAndSet: Remediation Instructions ───────────────────────────────────

Write-Host '╔══════════════════════════════════════════════════════════════╗' -ForegroundColor Yellow
Write-Host '║  IMPORTANT: AuditAndSet Mode — Remediation Task Required     ║' -ForegroundColor Yellow
Write-Host '╚══════════════════════════════════════════════════════════════╝' -ForegroundColor Yellow
Write-Host ''
Write-Host '  This config uses AuditAndSet (remediation) mode.' -ForegroundColor Yellow
Write-Host '  Existing machines need a remediation task after assignment:' -ForegroundColor Yellow
Write-Host ''
Write-Host '  Give the policy assignment a managed identity and its required role.' -ForegroundColor Gray
Write-Host '  DINE can deploy automatically for newly created or updated machines.' -ForegroundColor Gray
Write-Host ''
Write-Host '  After assigning the policy, you MUST create a remediation task:' -ForegroundColor Yellow
Write-Host ''
Write-Host '  Option A — Azure Portal:' -ForegroundColor Cyan
Write-Host '    1. Go to Policy > Assignments > select this assignment' -ForegroundColor Gray
Write-Host '    2. Click "Create Remediation Task"' -ForegroundColor Gray
Write-Host '    3. Wait for the task to complete (~15 min)' -ForegroundColor Gray
Write-Host ''
Write-Host '  Option B — PowerShell:' -ForegroundColor Cyan`);

    // Lines with PS $variables — use DLR constant to avoid JS template literal issues
    lines.push(
      "Write-Host \"    " + DLR + "assignment = Get-AzPolicyAssignment -Name 'MyAssignment' -Scope '/subscriptions/$subId'\" -ForegroundColor Gray",
      "Write-Host \"    Start-AzPolicyRemediation -Name '$configName-remediation' -PolicyAssignmentId " + DLR + "assignment.Id\" -ForegroundColor Gray",
      "Write-Host ''",
    );
  }

  // Summary
  lines.push(`
# ─── Summary ─────────────────────────────────────────────────────────────────

Write-Host "╔══════════════════════════════════════════════════════════════╗" -ForegroundColor Green
Write-Host "║  Done                                                        ║" -ForegroundColor Green
Write-Host "╚══════════════════════════════════════════════════════════════╝" -ForegroundColor Green
Write-Host ''
Write-Host "  Config:            $configName" -ForegroundColor White`);

  if (isRemediation) {
    lines.push(`Write-Host "  Mode:              AuditAndSet (Remediation)" -ForegroundColor White`);
  } else {
    lines.push(`Write-Host "  Mode:              Audit (Monitor Only)" -ForegroundColor White`);
  }

  lines.push(`Write-Host "  Hash:              $($hash.Substring(0,16))..." -ForegroundColor White
Write-Host "  Storage:           $StorageAccountName/$ContainerName/$blobName" -ForegroundColor White
Write-Host "  Policy Definition: $($policyDef.Id)" -ForegroundColor White
Write-Host ''
Write-Host '  Policy definition created. Assign it from Azure Portal.' -ForegroundColor Green
Write-Host '  Note: This script does not install the Guest Configuration extension. If it is already installed, no action is needed.' -ForegroundColor Gray
Write-Host '  If not installed, assign the prerequisites initiative (ID 12794019-7a00-42cf-95c2-882eed337cc8).' -ForegroundColor Gray`);

  if (isRemediation) {
    lines.push(`Write-Host '  Remember: Create a remediation task after assignment to enable remediation!' -ForegroundColor Yellow`);
  }

  lines.push(`Write-Host ''
Write-Host '  Or assign via PowerShell:'`);

  // More PS $variable lines
  lines.push(
    "Write-Host \"     " + DLR + "def = Get-AzPolicyDefinition -Name '$policyName'\" -ForegroundColor Gray",
  );

  if (isRemediation) {
    lines.push(
      "Write-Host \"     " + DLR + "assignment = New-AzPolicyAssignment -Name 'MyAssignment' -PolicyDefinition " + DLR + "def -Scope '/subscriptions/$subId' -Location '$Location' -IdentityType SystemAssigned\" -ForegroundColor Gray",
      "Write-Host \"     New-AzRoleAssignment -ObjectId " + DLR + "assignment.Identity.PrincipalId -RoleDefinitionId '088ab73d-1256-47ae-bea9-9de8e7131f31' -Scope '/subscriptions/$subId'\" -ForegroundColor Gray",
      "Write-Host '     # Allow identity/RBAC propagation before starting remediation.' -ForegroundColor Gray",
      "Write-Host \"     Start-AzPolicyRemediation -Name '" + safeName + "-remediation' -PolicyAssignmentId " + DLR + "assignment.Id\" -ForegroundColor Gray",
    );
  } else {
    lines.push(
      "Write-Host \"     New-AzPolicyAssignment -Name 'MyAssignment' -PolicyDefinition " + DLR + "def -Scope '/subscriptions/$subId'\" -ForegroundColor Gray",
    );
  }

  lines.push(`Write-Host ''
`);

  return lines.join('\n');
}
