import { ConfigurationState } from '../types';
import { assertValidIdentifiers } from '../utils/configuration';

export interface MetaconfigOutput {
  Type: ConfigurationState['mode'];
  Version: string;
}

/** Package metadata generated by New-GuestConfigurationPackage -Type -Version.
 * Runtime agent settings are supplied by the service, not authored in this file. */
export function generateMetaconfig(config: ConfigurationState): MetaconfigOutput {
  assertValidIdentifiers(config);
  return { Type: config.mode, Version: config.version };
}

export function generateMetaconfigString(config: ConfigurationState): string {
  return JSON.stringify(generateMetaconfig(config), null, 2);
}

export function getMetaconfigFilename(configName: string): string {
  return `${configName}.metaconfig.json`;
}
