import { ConfigurationState } from '../types';
import { schemasByName } from '../schemas';

/** Sanitise a string for safe embedding inside PowerShell single-quoted literals. */
function sanitisePs1String(value: string): string {
  return value
    .replace(/\0/g, '')           // strip null bytes
    .replace(/\r(?!\n)/g, '')     // strip lone CR (keep CRLF)
    .replace(/'/g, "''");         // escape single quotes for PS
}

/** Sanitise a DSC identifier (config name, module name).
 *  Must match [a-zA-Z_][a-zA-Z0-9_]* — strip anything else. */
function sanitiseIdentifier(value: string): string {
  const cleaned = value.replace(/[^a-zA-Z0-9_]/g, '');
  return /^[a-zA-Z_]/.test(cleaned) ? cleaned : `_${cleaned}`;
}

/** Collect unique modules used by the configuration's resources */
function getUniqueModules(config: ConfigurationState): { name: string; version: string }[] {
  const seen = new Map<string, string>();
  for (const resource of config.resources) {
    const schema = schemasByName[resource.schemaName];
    if (schema && !seen.has(schema.moduleName)) {
      seen.set(schema.moduleName, schema.moduleVersion);
    }
  }
  return Array.from(seen.entries()).map(([name, version]) => ({ name, version }));
}

/** Generate the package.ps1 helper script */
export function generatePackageScript(config: ConfigurationState): string {
  const packageType = config.mode === 'AuditAndSet' ? 'AuditAndSet' : 'Audit';
  const modules = getUniqueModules(config);
  const safeName = sanitiseIdentifier(config.configName);

  // Build a known-modules hashtable for the static path
  const knownModulesEntries = modules.map(m =>
    `    '${sanitisePs1String(m.name)}' = '${sanitisePs1String(m.version)}'`
  ).join('\n');

  return `# package.ps1 — Generated by Azure Machine Configuration Builder
# Run this script in PowerShell 7+ to create a deployable MC package
#
# What this does:
#   1. Detects required DSC modules from the MOF file
#   2. Installs them automatically (GuestConfiguration + all DSC resource modules)
#   3. Bundles the MOF + modules into a deployable .zip via New-GuestConfigurationPackage
#   4. Runs a local compliance test

#Requires -Version 7.0
$ErrorActionPreference = 'Stop'

$mofPath = Join-Path $PSScriptRoot '${safeName}.mof'
if (-not (Test-Path $mofPath)) {
    Write-Error "MOF file not found: $mofPath"
    exit 1
}

# ─── Detect Required Modules from MOF ───────────────────────────────────────
# Parse ModuleName/ModuleVersion pairs from the MOF's OMI_ConfigurationDocument
Write-Host '🔍 Detecting required DSC modules from MOF...' -ForegroundColor Cyan

$mofContent = Get-Content $mofPath -Raw

# Known modules from this build (fallback if MOF parsing misses anything)
$knownModules = @{
${knownModulesEntries}
}

# Parse the MOF for ModuleName/ModuleVersion references
$moduleRegex = [regex]'ModuleName\\s*=\\s*"(?<name>[^"]+)"\\s*;\\s*ModuleVersion\\s*=\\s*"(?<ver>[^"]+)"'
$matches = $moduleRegex.Matches($mofContent)
$requiredModules = @{}

foreach ($match in $matches) {
    $name = $match.Groups['name'].Value
    $ver = $match.Groups['ver'].Value
    if (-not $requiredModules.ContainsKey($name)) {
        $requiredModules[$name] = $ver
    }
}

# Merge known modules (in case MOF parsing missed any)
foreach ($key in $knownModules.Keys) {
    if (-not $requiredModules.ContainsKey($key)) {
        $requiredModules[$key] = $knownModules[$key]
    }
}

if ($requiredModules.Count -eq 0) {
    Write-Error "No DSC modules found in MOF. The MOF may be malformed."
    exit 1
}

Write-Host "   Found $($requiredModules.Count) module(s): $($requiredModules.Keys -join ', ')" -ForegroundColor Gray

# ─── Install Modules ────────────────────────────────────────────────────────
Write-Host '📦 Checking required modules...' -ForegroundColor Cyan

if (-not (Get-Module -ListAvailable -Name GuestConfiguration)) {
    Write-Host '   Installing GuestConfiguration...' -ForegroundColor Gray
    Install-Module -Name GuestConfiguration -Force -Scope CurrentUser -ErrorAction Stop
} else {
    Write-Host '   GuestConfiguration ✓' -ForegroundColor Gray
}

foreach ($modName in $requiredModules.Keys) {
    $modVer = $requiredModules[$modName]
    $existing = Get-Module -ListAvailable -Name $modName | Where-Object { $_.Version.ToString() -eq $modVer }
    if ($existing) {
        Write-Host "   $modName v$modVer ✓" -ForegroundColor Gray
    } else {
        Write-Host "   Installing $modName v$modVer..." -ForegroundColor Gray
        Install-Module -Name $modName -RequiredVersion $modVer -Force -Scope CurrentUser -ErrorAction Stop
    }
}

# ─── Create Package ──────────────────────────────────────────────────────────
$outputDir = Join-Path $PSScriptRoot 'output'
Write-Host "🔨 Creating MC package (Type: ${packageType})..." -ForegroundColor Cyan

$package = New-GuestConfigurationPackage \`
    -Name '${safeName}' \`
    -Configuration $mofPath \`
    -Path $outputDir \`
    -Type '${packageType}' \`
    -Force

# ─── Fix Module Structure (Azure GC requires versioned paths) ────────────────
# New-GuestConfigurationPackage sometimes creates flat Modules/ModuleName/ paths
# but the GC agent requires Modules/ModuleName/ModuleVersion/ — fix it in-place
Write-Host '🔧 Checking ZIP module structure...' -ForegroundColor Cyan
Add-Type -AssemblyName System.IO.Compression.FileSystem -ErrorAction SilentlyContinue

$zipPath = $package.Path
$needsRepair = $false

$zip = [System.IO.Compression.ZipFile]::OpenRead($zipPath)
$entries = $zip.Entries | ForEach-Object { $_.FullName }
$zip.Dispose()

foreach ($modName in $requiredModules.Keys) {
    $modVer = $requiredModules[$modName]
    $hasVersioned = $entries | Where-Object { $_ -like "Modules/$modName/$modVer/*" }
    if (-not $hasVersioned) {
        $hasFlat = $entries | Where-Object { $_ -like "Modules/$modName/*" }
        if ($hasFlat) {
            Write-Host "   ⚠️  $modName is flat — needs versioned subfolder" -ForegroundColor Yellow
            $needsRepair = $true
        }
    }
}

if ($needsRepair) {
    Write-Host '   Repackaging with versioned module paths...' -ForegroundColor Yellow
    $tmpStage = Join-Path ([System.IO.Path]::GetTempPath()) "zip-repair-$(Get-Random)"
    [System.IO.Compression.ZipFile]::ExtractToDirectory($zipPath, $tmpStage)

    foreach ($modName in $requiredModules.Keys) {
        $modVer = $requiredModules[$modName]
        $flatDir = Join-Path $tmpStage "Modules/$modName"
        $versionedDir = Join-Path $tmpStage "Modules/$modName/$modVer"
        if ((Test-Path $flatDir) -and -not (Test-Path $versionedDir)) {
            $tempMove = Join-Path ([System.IO.Path]::GetTempPath()) "mod-move-$(Get-Random)"
            Move-Item $flatDir $tempMove
            New-Item -ItemType Directory -Path $flatDir -Force | Out-Null
            Move-Item $tempMove $versionedDir
        }
    }

    Remove-Item $zipPath -Force
    [System.IO.Compression.ZipFile]::CreateFromDirectory($tmpStage, $zipPath)
    Remove-Item $tmpStage -Recurse -Force
    Write-Host '   ✅ Module paths fixed' -ForegroundColor Green
} else {
    Write-Host '   ✅ Module structure OK' -ForegroundColor Green
}

$hash = (Get-FileHash -Path $package.Path -Algorithm SHA256).Hash

Write-Host ''
Write-Host '✅ Package created successfully!' -ForegroundColor Green
Write-Host "   Path: $($package.Path)"
Write-Host "   Hash: $hash"
Write-Host ''

# ─── Local Compliance Test ───────────────────────────────────────────────────
Write-Host '🧪 Running local compliance test...' -ForegroundColor Cyan

# On Windows, the GC worker writes to C:\\ProgramData\\GuestConfig which requires elevation
$runningOnWindows = $PSVersionTable.PSVersion -and ($IsWindows -or $env:OS -eq 'Windows_NT')
$isElevated = if ($runningOnWindows) {
    ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
} else { $true }

if (-not $isElevated) {
    Write-Host '   ⚠️  Skipping — local compliance test requires Administrator privileges on Windows.' -ForegroundColor Yellow
    Write-Host '   Run this script in an elevated PowerShell to test locally, or deploy directly to Azure.' -ForegroundColor Gray
} else {
    try {
        $testCmd = if (Get-Command 'Test-GuestConfigurationPackage' -ErrorAction SilentlyContinue) {
            'Test-GuestConfigurationPackage'
        } else {
            'Get-GuestConfigurationPackageComplianceStatus'
        }
        $result = & $testCmd -Path $package.Path
        Write-Host "   Status: $($result.complianceStatus)" -ForegroundColor $(if ($result.complianceStatus -eq $true -or $result.complianceStatus -eq 'Compliant') { 'Green' } else { 'Yellow' })
        if ($result.resources) {
            foreach ($r in $result.resources) {
                $icon = if ($r.complianceStatus -eq $true -or $r.complianceStatus -eq 'True' -or $r.complianceStatus -eq 'Compliant') { '✅' } else { '❌' }
                Write-Host "   $icon $($r.properties.ConfigurationName) — $($r.complianceStatus)"
            }
        }
    } catch {
        Write-Host "   ⚠️  Local test failed: $($_.Exception.Message)" -ForegroundColor Yellow
        Write-Host '   This does not affect the package — deploy to Azure to validate.' -ForegroundColor Gray
    }
}
Write-Host ''

# ─── Next Steps ──────────────────────────────────────────────────────────────
Write-Host '📋 Next steps:' -ForegroundColor Cyan
Write-Host "   1. Upload output\\${safeName}.zip to Azure Blob Storage"
Write-Host '   2. Open policy.json — replace {{contentUri}} with the blob URL (SAS token)'
Write-Host "   3. Replace {{contentHash}} with: $hash"
Write-Host '   4. Create the policy definition:'
Write-Host "      New-AzPolicyDefinition -Name '${safeName}' -Policy '.\\policy.json' -Mode 'Indexed'"
Write-Host '   5. Assign the policy to your target scope'
Write-Host ''
Write-Host '⚠️  VM Prerequisites — assign this built-in initiative at subscription level:' -ForegroundColor Yellow
Write-Host '   "Deploy prerequisites to enable Guest Configuration policies on virtual machines"'
Write-Host '   Initiative ID: 12794019-7a00-42cf-95c2-882eed337cc8'
Write-Host '   Note: Arc-enabled servers already include the GC agent — no prerequisites needed.' -ForegroundColor Gray
Write-Host ''
`;
}
