import { ConfigurationState } from '../types';
import { schemasByName } from '../schemas';

/** Sanitise a string for safe embedding inside PowerShell single-quoted literals. */
function sanitisePs1String(value: string): string {
  return value
    .replace(/\0/g, '')           // strip null bytes
    .replace(/\r(?!\n)/g, '')     // strip lone CR (keep CRLF)
    .replace(/'/g, "''");         // escape single quotes for PS
}

/** Sanitise a DSC identifier (config name, module name).
 *  Must match [a-zA-Z_][a-zA-Z0-9_]* — strip anything else. */
function sanitiseIdentifier(value: string): string {
  const cleaned = value.replace(/[^a-zA-Z0-9_]/g, '');
  return /^[a-zA-Z_]/.test(cleaned) ? cleaned : `_${cleaned}`;
}

/** Collect unique modules used by the configuration's resources */
function getUniqueModules(config: ConfigurationState): { name: string; version: string }[] {
  const seen = new Map<string, string>();
  for (const resource of config.resources) {
    const schema = schemasByName[resource.schemaName];
    if (schema && !seen.has(schema.moduleName)) {
      seen.set(schema.moduleName, schema.moduleVersion);
    }
  }
  return Array.from(seen.entries()).map(([name, version]) => ({ name, version }));
}

/** Generate the package.ps1 helper script */
export function generatePackageScript(config: ConfigurationState): string {
  const packageType = config.mode === 'AuditAndSet' ? 'AuditAndSet' : 'Audit';
  const modules = getUniqueModules(config);
  const safeName = sanitiseIdentifier(config.configName);

  // Build a known-modules hashtable for the static path
  const knownModulesEntries = modules.map(m =>
    `    '${sanitisePs1String(m.name)}' = '${sanitisePs1String(m.version)}'`
  ).join('\n');

  return `# package.ps1 — Generated by Azure Machine Configuration Builder
# Run this script in PowerShell 7+ to create a deployable MC package
#
# What this does:
#   1. Detects required DSC modules from the MOF file
#   2. Installs them automatically (GuestConfiguration + all DSC resource modules)
#   3. Bundles the MOF + modules into a deployable .zip via New-GuestConfigurationPackage
#   4. Runs a local compliance test

#Requires -Version 7.0
$ErrorActionPreference = 'Stop'

$mofPath = Join-Path $PSScriptRoot '${safeName}.mof'
if (-not (Test-Path $mofPath)) {
    Write-Error "MOF file not found: $mofPath"
    exit 1
}

# ─── Detect Required Modules from MOF ───────────────────────────────────────
# Parse ModuleName/ModuleVersion pairs from the MOF's OMI_ConfigurationDocument
Write-Host '🔍 Detecting required DSC modules from MOF...' -ForegroundColor Cyan

$mofContent = Get-Content $mofPath -Raw

# Known modules from this build (fallback if MOF parsing misses anything)
$knownModules = @{
${knownModulesEntries}
}

# Parse the MOF for ModuleName/ModuleVersion references
$moduleRegex = [regex]'ModuleName\\s*=\\s*"(?<name>[^"]+)"\\s*;\\s*ModuleVersion\\s*=\\s*"(?<ver>[^"]+)"'
$matches = $moduleRegex.Matches($mofContent)
$requiredModules = @{}

foreach ($match in $matches) {
    $name = $match.Groups['name'].Value
    $ver = $match.Groups['ver'].Value
    if (-not $requiredModules.ContainsKey($name)) {
        $requiredModules[$name] = $ver
    }
}

# Merge known modules (in case MOF parsing missed any)
foreach ($key in $knownModules.Keys) {
    if (-not $requiredModules.ContainsKey($key)) {
        $requiredModules[$key] = $knownModules[$key]
    }
}

if ($requiredModules.Count -eq 0) {
    Write-Error "No DSC modules found in MOF. The MOF may be malformed."
    exit 1
}

Write-Host "   Found $($requiredModules.Count) module(s): $($requiredModules.Keys -join ', ')" -ForegroundColor Gray

# ─── Install Modules ────────────────────────────────────────────────────────
Write-Host '📦 Installing required modules...' -ForegroundColor Cyan

Install-Module -Name GuestConfiguration -Force -Scope CurrentUser -ErrorAction Stop

foreach ($modName in $requiredModules.Keys) {
    $modVer = $requiredModules[$modName]
    Write-Host "   Installing $modName v$modVer..."
    Install-Module -Name $modName -RequiredVersion $modVer -Force -Scope CurrentUser -ErrorAction Stop
}

# ─── Create Package ──────────────────────────────────────────────────────────
$outputDir = Join-Path $PSScriptRoot 'output'
Write-Host "🔨 Creating MC package (Type: ${packageType})..." -ForegroundColor Cyan

$package = New-GuestConfigurationPackage \`
    -Name '${safeName}' \`
    -Configuration $mofPath \`
    -Path $outputDir \`
    -Type '${packageType}' \`
    -Force

$hash = (Get-FileHash -Path $package.Path -Algorithm SHA256).Hash

Write-Host ''
Write-Host '✅ Package created successfully!' -ForegroundColor Green
Write-Host "   Path: $($package.Path)"
Write-Host "   Hash: $hash"
Write-Host ''

# ─── Local Compliance Test ───────────────────────────────────────────────────
Write-Host '🧪 Running local compliance test...' -ForegroundColor Cyan
$testCmd = if (Get-Command 'Test-GuestConfigurationPackage' -ErrorAction SilentlyContinue) {
    'Test-GuestConfigurationPackage'
} else {
    'Get-GuestConfigurationPackageComplianceStatus'
}
$result = & $testCmd -Path $package.Path
Write-Host "   Status: $($result.complianceStatus)" -ForegroundColor $(if ($result.complianceStatus -eq $true -or $result.complianceStatus -eq 'Compliant') { 'Green' } else { 'Yellow' })
if ($result.resources) {
    foreach ($r in $result.resources) {
        $icon = if ($r.complianceStatus -eq $true -or $r.complianceStatus -eq 'True' -or $r.complianceStatus -eq 'Compliant') { '✅' } else { '❌' }
        Write-Host "   $icon $($r.properties.ConfigurationName) — $($r.complianceStatus)"
    }
}
Write-Host ''

# ─── Next Steps ──────────────────────────────────────────────────────────────
Write-Host '📋 Next steps:' -ForegroundColor Cyan
Write-Host '   1. Upload output/${safeName}.zip to Azure Blob Storage'
Write-Host '   2. Open policy.json — replace {{contentUri}} with the blob URL (SAS token)'
Write-Host "   3. Replace {{contentHash}} with: $hash"
Write-Host '   4. Create the policy definition:'
Write-Host "      New-AzPolicyDefinition -Name '${safeName}' -Policy '.\\policy.json' -Mode 'All'"
Write-Host '   5. Assign the policy to your target scope'
Write-Host ''
Write-Host '⚠️  VM Prerequisites — assign this built-in initiative at subscription level:' -ForegroundColor Yellow
Write-Host '   "Deploy prerequisites to enable Guest Configuration policies on virtual machines"'
Write-Host '   Initiative ID: 12794019-7a00-42cf-95c2-882eed337cc8'
Write-Host ''
`;
}
