import { ConfigurationState } from '../types';
import { schemasByName } from '../schemas';

/** Collect unique modules used by the configuration's resources */
function getUniqueModules(config: ConfigurationState): { name: string; version: string }[] {
  const seen = new Map<string, string>();
  for (const resource of config.resources) {
    const schema = schemasByName[resource.schemaName];
    if (schema && !seen.has(schema.moduleName)) {
      seen.set(schema.moduleName, schema.moduleVersion);
    }
  }
  return Array.from(seen.entries()).map(([name, version]) => ({ name, version }));
}

/** Generate README.md for the package bundle */
export function generateReadme(config: ConfigurationState): string {
  const isWindows = config.platform === 'Windows';
  const modules = getUniqueModules(config);
  const moduleListStr = modules.map(m => `${m.name} v${m.version}`).join(', ');
  const extensionPolicy = isWindows ? '385f5831-96d4-41db-9a3c-cd3af78aaae6' : '331e8ea8-378a-410f-a2e5-ae22f38bb0da';

  return `# ${config.configName}

> Generated by [Azure Machine Configuration Builder](https://petarivanov-msft.github.io/azure-mc-builder/)

## Overview

- **Platform:** ${config.platform}
- **Mode:** ${config.mode === 'AuditAndSet' ? 'Apply (AuditAndSet)' : 'Audit'}
- **Version:** ${config.version}
- **Resources:** ${config.resources.length}
- **DSC Modules:** ${moduleListStr}
${config.description ? `\n${config.description}\n` : ''}
## Files

| File | Description |
|------|-------------|
| \`${config.configName}.mof\` | Compiled MOF configuration (what the MC agent evaluates) |
| \`${config.configName}.ps1\` | PowerShell DSC Configuration script (source, for reference) |
| \`metaconfig.json\` | MC agent behavior (reference copy — package.ps1 embeds this automatically) |
| \`policy.json\` | Azure Policy definition (AuditIfNotExists) |
| \`package.ps1\` | Helper script — creates deployable package and tests locally |
| \`README.md\` | This file |

## Quick Start

### Prerequisites

- PowerShell 7.x — run \`pwsh\`, not \`powershell\` ([install](https://learn.microsoft.com/powershell/scripting/install/installing-powershell))
- Az PowerShell module (\`Install-Module Az -Scope CurrentUser\`) for upload and policy steps
- Azure subscription with Resource Policy Contributor role
- Storage account for hosting packages

> **Author packages on your workstation**, not on target VMs. PowerShell 7 is cross-platform — you can build ${isWindows ? 'Windows' : 'Linux'} packages from any OS.

### 1. Create the Package

\`\`\`powershell
pwsh ./package.ps1
\`\`\`

This installs \`GuestConfiguration\` and the required DSC modules (${modules.map(m => `\`${m.name}\``).join(', ')}), creates a deployable .zip from the pre-generated MOF, and runs a local compliance test.

### 2. Upload to Azure Blob Storage

The container can stay private — the SAS token provides read access for the GC agent.

\`\`\`powershell
$ctx = (Get-AzStorageAccount -ResourceGroupName 'myRG' -Name 'mystorageaccount').Context

Set-AzStorageBlobContent -Container 'guestconfiguration' \\
  -File '.\\output\\${config.configName}.zip' -Context $ctx

$uri = New-AzStorageBlobSASToken -Container 'guestconfiguration' \\
  -Blob '${config.configName}.zip' -Permission r \\
  -ExpiryTime (Get-Date).AddYears(3) -Context $ctx -FullUri
\`\`\`

### 3. Get the Content Hash

\`\`\`powershell
$hash = (Get-FileHash '.\\output\\${config.configName}.zip' -Algorithm SHA256).Hash
\`\`\`

### 4. Create and Assign the Policy

1. Open \`policy.json\` and replace \`{{contentUri}}\` with the SAS URL and \`{{contentHash}}\` with the hash
2. Create the policy definition:

\`\`\`powershell
New-AzPolicyDefinition -Name '${config.configName}' -Policy '.\\policy.json' -Mode 'Indexed'
\`\`\`

3. Assign it:

\`\`\`powershell
$def = Get-AzPolicyDefinition -Name '${config.configName}'
New-AzPolicyAssignment -Name '${config.configName}' -PolicyDefinition $def \\
  -Scope '/subscriptions/<subscription-id>'
\`\`\`

## Azure Prerequisites

These must be in place **before** your custom policy will evaluate:

### 1. Register the resource provider

\`\`\`powershell
az provider register --namespace Microsoft.GuestConfiguration
\`\`\`

### 2. Deploy prerequisites to VMs

Assign the built-in initiative **"Deploy prerequisites to enable Guest Configuration policies on virtual machines"**:

\`\`\`
Initiative ID: 12794019-7a00-42cf-95c2-882eed337cc8
\`\`\`

This single initiative handles everything — MC extension (Windows & Linux) and system-assigned managed identity.

> **Individual policy IDs** (if you prefer granular assignments): GC Extension — \`${extensionPolicy}\`, Managed Identity — \`3cf2ab00-13f1-4d0c-8971-2ac904541a7e\`

## Resources in This Configuration

${config.resources.map((r, i) => `${i + 1}. **[${r.schemaName}] ${r.instanceName}**`).join('\n')}
${!isWindows ? `
## Linux Note

This configuration uses the [\`nxtools\`](https://github.com/Azure/nxtools) module (v1.6.0) — the official DSC resource module for Azure Machine Configuration on Linux. Do **not** use the legacy \`nx\` module from PSGallery — it contains only schema files with no implementation and will fail.
` : ''}
## Troubleshooting

| Symptom | Cause | Fix |
|---------|-------|-----|
| Compliance stuck at "Not started" | MC extension or identity missing | Assign the prerequisites initiative |
| \`GuestConfigurationAssignmentValidationFailed\` | Hash mismatch | Regenerate hash and update policy |
| \`couldn't find PowerShell DSC resource\` | Wrong module (Linux: \`nx\` instead of \`nxtools\`) | Rebuild with this builder |
| No results after 30 min | First eval can be slow | Check \`${isWindows ? 'C:\\\\ProgramData\\\\GuestConfig\\\\gc_agent_logs\\\\gc_agent.log' : '/var/lib/GuestConfig/gc_agent_logs/gc_agent.log'}\` |

## Timing

- The MC agent evaluates every **~15 minutes**
- First results typically appear within **5–15 minutes** of assignment
- After a fresh policy assignment, allow up to **30 minutes** for the full cycle (extension install → download → evaluate → report)
`;
}
