import { ConfigurationState } from '../types';
import { schemasByName } from '../schemas';
import { assertValidIdentifiers } from '../utils/configuration';

/** Collect unique modules used by the configuration's resources */
function getUniqueModules(config: ConfigurationState): { name: string; version: string }[] {
  const seen = new Map<string, string>();
  for (const resource of config.resources) {
    const schema = schemasByName[resource.schemaName];
    if (schema && !seen.has(schema.moduleName)) {
      seen.set(schema.moduleName, schema.moduleVersion);
    }
  }
  return Array.from(seen.entries()).map(([name, version]) => ({ name, version }));
}

/** Generate README.md for the package bundle */
export function generateReadme(config: ConfigurationState): string {
  assertValidIdentifiers(config);
  const isWindows = config.platform === 'Windows';
  const modules = getUniqueModules(config);
  const moduleListStr = modules.map(m => `${m.name} v${m.version}`).join(', ');
  const extensionPolicy = isWindows ? '385f5831-96d4-41db-9a3c-cd3af78aaae6' : '331e8ea8-378a-410f-a2e5-ae22f38bb0da';

  return `# ${config.configName}

> Generated by [Azure Machine Configuration Builder](https://petarivanov-msft.github.io/azure-mc-builder/)

## Overview

- **Platform:** ${config.platform}
- **Mode:** ${config.mode === 'AuditAndSet' ? 'Apply (AuditAndSet)' : 'Audit'}
- **Version:** ${config.version}
- **Resources:** ${config.resources.length}
- **DSC Modules:** ${moduleListStr}
${config.description ? `\n${config.description}\n` : ''}
## Files

| File | Description |
|------|-------------|
| \`${config.configName}.mof\` | Compiled MOF configuration (what the MC agent evaluates) |
| \`${config.configName}.ps1\` | PowerShell DSC Configuration script (source, for reference) |
| \`${config.configName}.metaconfig.json\` | Package Type and Version, read by package.ps1 and passed to the official packaging cmdlet |
| \`policy.json\` | Azure Policy definition (AuditIfNotExists or DeployIfNotExists) |
| \`package.ps1\` | Helper script — creates deployable package |
| \`deploy.ps1\` | Uploads the package and creates or updates the policy definition in place |
| \`README.md\` | This file |

## Quick Start

### Prerequisites

- PowerShell 7.x — run \`pwsh\`, not \`powershell\` ([install](https://learn.microsoft.com/powershell/scripting/install/installing-powershell))
- Az PowerShell module (\`Install-Module Az -Scope CurrentUser\`) for upload and policy steps
- Azure subscription with Resource Policy Contributor role
- Storage account for hosting packages, with Storage Blob Data Contributor at account scope

> **Author packages on your workstation**, not on target VMs. PowerShell 7 is cross-platform — you can build ${isWindows ? 'Windows' : 'Linux'} packages from any OS.

### 1. Create the Package

\`\`\`powershell
pwsh ./package.ps1
\`\`\`

This installs \`GuestConfiguration\` and the required DSC modules (${modules.map(m => `\`${m.name}\``).join(', ')}), then creates a deployable .zip from the pre-generated MOF.
The official cmdlet writes the packaged metaconfig using the Type and Version supplied by \`package.ps1\`. Change the builder configuration and re-export the bundle to update these values together with the policy.

### 2. Upload to Azure Blob Storage

Recommended: run \`pwsh ./deploy.ps1 -StorageAccountName 'YourStorageAccount'\`. It uses Microsoft Entra ID without listing account keys, uploads the exact package, and fills both policy placeholders. Existing-account uploads do not require permission to list storage accounts.
The container stays private. By default the read-only user delegation SAS expires in **6 days**; renew it and re-run deployment before expiry. There is no automatic Shared Key fallback.
For an explicitly approved long-lived service SAS, use \`-StorageAuthMode SharedKey -SasExpiryDays 1095\`. This requires account-key access and Shared Key authentication enabled. Storage SAS-expiration policies may impose a shorter limit.

Manual upload:

\`\`\`powershell
$ctx = New-AzStorageContext -StorageAccountName 'YourStorageAccount' -UseConnectedAccount

Set-AzStorageBlobContent -Container 'guestconfiguration' -File '.\\output\\${config.configName}.zip' -Blob '${config.configName}.zip' -Context $ctx

$uri = New-AzStorageBlobSASToken -Container 'guestconfiguration' -Blob '${config.configName}.zip' -Permission r -Protocol HttpsOnly -StartTime (Get-Date).AddMinutes(-5) -ExpiryTime (Get-Date).AddDays(6) -Context $ctx -FullUri
\`\`\`

### 3. Get the Content Hash

\`\`\`powershell
$hash = (Get-FileHash '.\\output\\${config.configName}.zip' -Algorithm SHA256).Hash
\`\`\`

### 4. Create and Assign the Policy

1. Open \`policy.json\` and replace \`{{contentUri}}\` with the SAS URL and \`{{contentHash}}\` with the hash
2. Create the policy definition:

\`\`\`powershell
New-AzPolicyDefinition -Name 'MC-${config.configName}' -Policy '.\\policy.json' -Mode 'Indexed'
\`\`\`

3. Assign it:

\`\`\`powershell
$def = Get-AzPolicyDefinition -Name 'MC-${config.configName}'
${config.mode === 'AuditAndSet'
    ? `$assignment = New-AzPolicyAssignment -Name '${config.configName}' -PolicyDefinition $def -Scope '/subscriptions/<subscription-id>' -Location 'uksouth' -IdentityType SystemAssigned
New-AzRoleAssignment -ObjectId $assignment.Identity.PrincipalId -RoleDefinitionId '088ab73d-1256-47ae-bea9-9de8e7131f31' -Scope '/subscriptions/<subscription-id>'
Start-AzPolicyRemediation -Name '${config.configName}-remediation' -PolicyAssignmentId $assignment.Id`
    : `New-AzPolicyAssignment -Name '${config.configName}' -PolicyDefinition $def -Scope '/subscriptions/<subscription-id>'`}
\`\`\`

${config.mode === 'AuditAndSet' ? 'Creating the role assignment requires role-assignment write permissions; allow identity/RBAC propagation before starting remediation. The portal can guide you through these steps instead.\n' : ''}
### Updating a Release

Increment the version in the builder, re-export, then run \`package.ps1\` and \`deploy.ps1\` again. Deployment uses a content-addressed blob name and updates the existing definition without deleting assignments. Both the content URI and SHA256 hash are replaced, including DINE deployment parameters.

Fixed values stay in the MOF, not in policy parameter overrides. Metadata \`configurationParameter\` is an object mapping; the assignment property is an array. The compliance-only existence condition matches the official cmdlet for configurations without policy parameters; a parameterHash is not a package-content hash.

These policies target individual Azure VMs and Arc-enabled servers, not VM scale sets.

## Azure Prerequisites

These must be in place **before** your custom policy will evaluate:

### 1. Register the resource provider

\`\`\`powershell
Register-AzResourceProvider -ProviderNamespace Microsoft.GuestConfiguration
\`\`\`

### 2. Deploy prerequisites to VMs

Assign the built-in initiative **"Deploy prerequisites to enable Guest Configuration policies on virtual machines"**:

\`\`\`
Initiative ID: 12794019-7a00-42cf-95c2-882eed337cc8
\`\`\`

This single initiative handles everything — MC extension (Windows & Linux) and system-assigned managed identity. Arc-enabled servers already include the GC agent — no prerequisites needed.

> **Individual policy IDs** (if you prefer granular assignments): GC Extension — \`${extensionPolicy}\`, Managed Identity — \`3cf2ab00-13f1-4d0c-8971-2ac904541a7e\`

## Resources in This Configuration

${config.resources.map((r, i) => `${i + 1}. **[${r.schemaName}] ${r.instanceName}**`).join('\n')}
${!isWindows ? `
## Linux Note

This configuration uses the [\`nxtools\`](https://github.com/Azure/nxtools) module (v1.6.0) — the official DSC resource module for Azure Machine Configuration on Linux. Do **not** use the legacy \`nx\` module from PSGallery — it contains only schema files with no implementation and will fail.
` : ''}
## Troubleshooting

| Symptom | Cause | Fix |
|---------|-------|-----|
| Compliance stuck at "Not started" | MC extension or identity missing | Assign the prerequisites initiative |
| \`GuestConfigurationAssignmentValidationFailed\` | Hash mismatch | Regenerate hash and update policy |
| \`couldn't find PowerShell DSC resource\` | Wrong module (Linux: \`nx\` instead of \`nxtools\`) | Rebuild with this builder |
| No results after 30 min | First eval can be slow | Check \`${isWindows ? 'C:\\\\ProgramData\\\\GuestConfig\\\\gc_agent_logs\\\\gc_agent.log' : '/var/lib/GuestConfig/gc_agent_logs/gc_agent.log'}\` |

## Timing

- The MC agent evaluates every **~15 minutes**
- First results typically appear within **5–15 minutes** of assignment
- After a fresh policy assignment, allow up to **30 minutes** for the full cycle (extension install → download → evaluate → report)
`;
}
