/*
@TargetNode='localhost'
@GeneratedBy=WinRegistryAuditManual
@GenerationDate=04/01/2026 11:42:57
@GenerationHost=AzureMCBuilder
*/

instance of MSFT_RegistryResource as $MSFT_RegistryResource1ref
{
    ResourceID = "[Registry]WinVer";
    Key = "HKLM:\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion";
    ValueName = "ProductName";
    Ensure = "Present";
    SourceInfo = "WinRegistryAuditManual::Registry::WinVer";
    ModuleName = "PSDscResources";
    ModuleVersion = "2.12.0.0";
    ConfigurationName = "WinRegistryAuditManual";
};

instance of OMI_ConfigurationDocument
{
    Version = "2.0.0";
    MinimumCompatibleVersion = "1.0.0";
    CompatibleVersionAdditionalProperties = {"Omi_BaseResource:ConfigurationName"};
    Author = "WinRegistryAuditManual";
    GenerationDate = "04/01/2026 11:42:57";
    GenerationHost = "AzureMCBuilder";
    Name = "WinRegistryAuditManual";
};
